package antlr.preprocessor;
/* loaded from: classes.dex */
public interface PreprocessorTokenTypes {
    public static final int ACTION = 6;
    public static final int ALT = 27;
    public static final int ARG_ACTION = 19;
    public static final int ASSIGN_RHS = 13;
    public static final int BANG = 18;
    public static final int CHAR_LITERAL = 36;
    public static final int COMMA = 23;
    public static final int COMMENT = 33;
    public static final int CURLY_BLOCK_SCARF = 30;
    public static final int DIGIT = 39;
    public static final int ELEMENT = 28;
    public static final int EOF = 1;
    public static final int ESC = 38;
    public static final int HEADER_ACTION = 5;
    public static final int ID = 8;
    public static final int ID_OR_KEYWORD = 29;
    public static final int LITERAL_catch = 25;
    public static final int LITERAL_class = 7;
    public static final int LITERAL_exception = 24;
    public static final int LITERAL_extends = 9;
    public static final int LITERAL_private = 16;
    public static final int LITERAL_protected = 15;
    public static final int LITERAL_public = 17;
    public static final int LITERAL_returns = 20;
    public static final int LITERAL_throws = 22;
    public static final int LITERAL_tokens = 4;
    public static final int ML_COMMENT = 35;
    public static final int NEWLINE = 32;
    public static final int NULL_TREE_LOOKAHEAD = 3;
    public static final int OPTIONS_START = 12;
    public static final int RCURLY = 14;
    public static final int RULE_BLOCK = 21;
    public static final int SEMI = 10;
    public static final int SL_COMMENT = 34;
    public static final int STRING_LITERAL = 37;
    public static final int SUBRULE_BLOCK = 26;
    public static final int TOKENS_SPEC = 11;
    public static final int WS = 31;
    public static final int XDIGIT = 40;
}
