package com.explorestack.iab.utils;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.util.Base64;
import androidx.core.view.ViewCompat;
/* loaded from: classes2.dex */
public class Assets {
    public static final String close = "iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAACY0lEQVR4Ae3aAWRbURTH4YNiKIqggKEYCiiKYQQABQAMARRBAVAADEEBUAAEAADBAMMwBADFADAURXYQoZdoOLie+338PQK4fnmJ5wUAAAAAAAAAAAAAAAAAAAAAAHACrnJ3uWVunpvFuM5zX3Pf99fz4KiL3HNu1+w195A7i3Gc5R5zb81ZvO0/b86CWe6ljafZZpBv4GXu9wdn8UtE761zuxP2sxrRBOLZnngWjznSbXs4g0Z0Sjztz9lFEPe5XT2iIeJp9y2IVW5Xj2iMeJotguYOVIlogHiazYO4ye3qEQ0VT/MfiPUAEZXjafYjDpjl/k41og7x/Ml9inf4MsWIOsSzzV0G40QkHhGJR0Ti6U9E4hGRePoTkXhEJJ7+RCQeEYmnPxGJR0TiqROReOpEJJ46EYmnTkTiqROReMpEJJ4CEYmnQETiKRGReEpEJJ4kIvH0JyLxiEg8/YlIPCIST38iEo+IxEP9ZbA+L6UhHhGJR0T9iUdE4hFRf+IRkXhE1It4RNQQz7bysFFE4rksPLEWkXj2RFQgHhGViUdEZeIRUZl4RFQmHhGViUdEZeIRkXjqRCQeEXUnHhGJR0T9iUdE4hFRf+IRkXhEJJ5uRCQeEYlHROM47x/PpCLa5M7igKf+8Uwuoodc4rp/PJOM6DU3i2DRP57JRjSPYNU/nslGtIxgOXA81YjuIpgPHk8loqtcYjNqPIWInuOAz7l/o8VTiOgldxENER2/Ez0N9vR1llsfOYt1bhZHMc8tc6vcIncd47rJ3edW++ttAAAAAAAAAAAAAAAAAAAAAAAAfOA/5Zwc/aYfb7AAAAAASUVORK5CYII=";
    public static final IabElementStyle defBannerStyle;
    public static final float defCircleElementSize = 30.0f;
    public static final IabElementStyle defCloseStyle;
    public static final IabElementStyle defCountDownProgressStyle;
    public static final IabElementStyle defCountDownStyle;
    public static final IabElementStyle defCtaStyle;
    public static final float defHideAfterSec = 3.0f;
    public static final IabElementStyle defInlineBannerStyle;
    public static final IabElementStyle defLinearProgressStyle;
    public static final IabElementStyle defLoadingStyle;
    public static final IabElementStyle defMuteStyle;
    public static final IabElementStyle defRepeatStyle;
    public static final IabElementStyle defSkipStyle;
    public static final IabElementStyle defTextCountDownStyle;
    public static final IabElementStyle defTextProgressStyle;
    public static final IabElementStyle defVideoStyle;
    public static final String mute = "iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAMAAADQmBKKAAAAw1BMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAcKsgAAAAQXRSTlMABFeXn38wGNP/u0AMw8tP11+/3/eTOPNH+0tnc3fvb+tDi49TEKMcY8drKCCvFJt7qyQ047eHCCw8g89bp9vns9m2qsEAAAOSSURBVHgB7drVYuNKEEXR03YMJ0aBQXHAYWbm/P9PXZyZBimOHiTVQK9H4zZDFTzP8zzP8zzP83JQtfpSo4mfRqvNfy138HPo9vhNf4CfQYPaMFAQF9IUdSAtpm3UhSza5O+kmBb5O6nPtGgMOQNmmEwhp84MSQ0VUCuz1bGCQ62tM8MGSlebk+RwE67WVlbSNkq2xf8lO0jZbWQk7SmUaZvfxS3kS6pX00NuIct+SNdBNT08RLajmLakU0kP1/GJ40Pa5idV9JD4jBrR1u5W0UN8rkHbaRU9xAIbtM0q6CEWqSU0rZ+V30MstGMXnZffQyx2Qcu49B7iC5c09UvvIb7QbdN0UHYP8ZWrdRrmuyX3EIbDa2TYoalRcg9hIM/PkLZMw40qt8cJYtREynFCw6DcHjeIcfDF+W/L7UkFkRtw7c5pOCm1xw3KLprRcIfc1MFyxMXyBHEGx/06tfk9cmr1SRYRlFzDMaJhBzmFLCiIURe2BxrqyGfGwoK4B8chtTbyWS4wiI+wBTTsIpf1IoNC2O5jagPkwiKDOFjwBN2SCAphe6J2KBHEE1im1JJ7iaAGLLs0jCWChrA9UwskgngGy4jakUjQCiwNag2RoCdYZtTqIkGXsLxQ2xMJCmHpUAtFgtqwNKk9iwRFsJxQi0SCbmDZt46SCBrC8uA+mv5JfQpLjdqrSNAWLAfUzkWCBj/bR8c+LNvUNiSCItgOpb9+bMHSTah1JIIeYOnQsCsQ1IftgtozBIIC2G6pbQsEPStY1IRaDbm8FRm0AtsODS3k8lRg0C0WPGJvyGc3KizovQXbCQ1LyOn4uaigKRx3NATIS631JkUEPcGh3qlNulX/6bkNV42GUdV/C6d77iMaHqr94zy5+GJodljtaGG+iZT9mIaXSocvp/tIe6Vhfl/heGq4iQwdmraqHOApZGjd0DDZlx5xqpCmNfEh8IimNyU9Jg9omUovEjzGNJ1Kr1o8TmiKT4SXUXYSWi6E13UCp6enRBeasErbTUt05evskrZJE6igqI9sK3M6akAVRSNk6S7R1QCqKEqukKaCiK5ToJKig6ycN6aEXZRrFpPkzQ5c90dvTLtUKFv3pXExvYfrJWKGbQUh28yy9nOtwCcHENNj2voAciZM+diHILrWA4gSv3tc7/J3j61u5jTOIG5/zm/eN+7xM7i+4b/eAoWfRHf1I1wawPM8z/M8z/M872/KUtAsVj+VvQAAAABJRU5ErkJggg==";
    public static final String repeat = "iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAMAAADQmBKKAAAAw1BMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAcKsgAAAAQXRSTlMAJJeDLG/7//NAr9/Dv6tHGO8cYxRbDFOjS7u3y/d7BNef67PjIHeTz9swj0M401co52vHi3NPp5sQNH9nXzwIhxbEf6oAAAOpSURBVHgB7M5FAcAwAMDAcUYd+9e6Zy2kcAquKUBVVVXVdv3QiIwTzIvoA8Aq+zDLPmD7YPtg+2D7YPtg+2D7YPtg+2D7YPtg+2D7YPtg+2D7sG17OLrxvCSf6N7HR/KJwvupPsD0t2uX28rjABSGN9YNhCO4lnKQ44K73f9Njc+kpQyWtHR9i+c38tbbNMl8AV4r8izxUhneqvBc1RC8VOPZzLoVjF1IaiTgGeuel3jKBa2omQ1aEVuFoBWlfC9qdxL555fWazMoRQL/CNXfAlEkIL1/tOn2+uhrkYDDZ4kuDV+LBHZ8fV+3SGCX9Wy6inzcjwTcOlXueIFvRQL7/DTplPCtSGCvbo8OouBXkcBpRS/wqUjgxKKED0UHg9AVPm00WXQ4CI8NnzaaLDochE6cdglfigQO6NNuAD+KBA65o13Xj6LDQR2TNkP4UFTBQSPaNC3vi4wxDrIGtCnCW+Pq5BNHdA1KVQRAkpKRwfWNaVPH9VlNSgIB8EGbT1xflDbPCIAapSkCoE8phQAIUWoiCAxKMwTAG6U5AqBK6QcBEKYUQQCMKE0QsMtZDQHwHrSrWUc1KDptiMpiBl3mlO4unFtGspeAJmVKSZxtyX+ku9BjRekJ55ql3atX0ULpPLSk1NF/YhwpfXsFLe6VfnLq3uCqUpQelDaZgBZtSmu1W+AONMgo/mKa0hIaZGlTUHvUnOjep78V37D2oM6KK47IvFPvHWdC+UExTSmpd4uZG9XxCkahKKQ+HhOjznPjC21iyg92NEJQkjNpE8JFkhpXUYQaRtDe9a2id4M2Dzqe7FixcDHnmOernlMHt8pPZOp3M3fUsqZDJm16G1zsgXbNDi6Sa1DbiOcr7WoWLrBJaXxhNqZDGBeY0KEMJVU6TCy10Vf1O5lcmw6pGc5ilejQzEHR2qBDI4MzzFJ0WkHZiE69d5ws1KBTFRok6RRfWjhNP+3JdJSZ4I7vBE7QTXFHswst5gZ33YdwxMY9OcZcQ5MlXcztDAc8RtJ0+YE2K4Mu5v/PB45OTbrVodFDnDytqVAOC+6zgFbzHvcyU6Vtv/iVwaaTyI+Gk4HJvYw8NAs1qCC9hnaPA17srQsPFFq8UOoR3sj2eIF0H56ZDQ2eq5WBl7pVnqVXhNfKbzxZ+mMG723qTZ5ExGbwh/U5Pd5U+7Hgo824FD9Us/2Cf2RTk3v0SvlHXEshWl5uJ4M2aYha9SkSyyeiCAJrhl/Tzc3Nzc3Nzc3N7+6ZjDHKAbJeAAAAAElFTkSuQmCC";
    public static final String skip = "iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAACoklEQVR4Ae3dAUScYRzH8eEQDiEMQxiGIQxhiGEIIQxhGEIIIQzDMAwhDMMQhiEMMIQhhABhCCGEEMLh9gMwi65nPau/z4cvAH784bx37z0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAALiOx+llWkqzxXYtpMU0k/4x5tNBGv/RXpq/57v2/7JrNz1NQauVNErjKxql92lQcNdGasDTdJnG1+ggPS64ay89StzAlzSeoIv0puCu87ScJsRpGt+g3TRTcNdOGqZrYtzQSXpZcNdxep5aOKAJ2kpTBXY1fHBwQK0dprkCuxo+ODig1i7TesFdF2k1tXBAE/QjPSqwq+GDgwNq7SwtFdx1mhZTCwc0QZ/TsOCu7TSVHFCHfqX5gruO0pwD6tMovU2Dgrs20sAB9Wk/zdbZ5Xna+D90kVYK7jpPrxxQv76l6YK7dtK0A+rTSVq4v7s8TxvfkT6mQbFdo/QhDRxQnw7Tk4K7DtITB9Sny7RWcNdFWnNA/fqeHhbdNeOA+nSWFu1yQK19SsOCu7bT0AF1fO5klwNqaZReV93lgPq1XHhXBw7oLE1V3eWA+rRYeFcHDuhd2V13nwNyQA5opfAuB9Thedmw/q7b4oA26u+6LQ5oq/6u2+CAztOKXTfhgH6mWbsm5YBGaTMN7JqUAzpKz+xyQO3f/7HLAbV/U88uB9T+HWi7HFDjrxXsckBNvwOzywG1/GLTLgd0nBbsugkH9DVN21XLnX5vjl0OaC/N2lXUXXzeY5cDOkpzdjmg9t9721Vb1Te4d3qORYd33thVWeF/sem0i7OW9/7ZxW7L8x67mE+jlncf28Vm69vX7WI5nV7xV03LdnEdg/Qirab1tJAGdgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdPQbak6roi3sq5YAAAAASUVORK5CYII=";
    public static final String unmute = "iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAMAAADQmBKKAAAAwFBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALOy8QAAAAQHRSTlMAT5vPRxSr/1OTn4c4s9cYEMu/XwTDu3fbYwjvt+NA8wwg3/fHKOdLj/tbPDBv03+jl4sca2d7NCTrLINDr6dz72VdRQAAA8FJREFUeAHt2dWW6zgURdEd3GFmZqZi7O7//6rmW7ZiK2VHkYo8X0MreI5GENAiEAgEAoFAIBAIhSORcBSfRSzOf8VjOFMimUpncDFZ/i+XxzkKRZJkKYrLKJNKRZUq/xdJVKAONaoV1WlpNFtQ1qZaUYd23R5U9alUVOlTlBxATZVKRUMeG/WgpE61ojEF6i9SJaJWNKHTKAMF05lSUYgu+vMPLFrQxXJlpGhdLm/gsG3TxVZ/UbRLkrsejhX2bkkL3UVb/meZgLekQ0VrUb7P/43z8JZ0Ba1F67eia7i5qfFY01DRBO5uxxQte2aK2pCYFimaDc0UQaaSpCgyMFIEuT1FcZgowglbiu5MFOGU1ZJ27ZiBIpyUEIvC0F+E0+5pt3zQX4R3xGk3gfYivGOwo11TU5EPj23aPBVMFk0e4CJBuz0MFpHh2DvnT3YrBotIjjZweF7SZg5zRSQ5LsMhSZsslKV4XDSAK9kGXXiizRCKFnSouhdRVnRHmzQ8qzRrI0p4KZIO0VabllkFHuWLFPgukk+IJG1C8KhEqhXxl9EAoudzFv47UrGIbw6njv0ReFOjalGfb9YQlWlTgCdtqhatraISRK2x/w8Recmi0IkPaNp/kHpRCaIX/1sRL1s0hCBKy7LlP0i9aA9BgTYZfUHyohxEEVrKGoPkRTH5j/WtziBp0Vx+jt1rDZIVvcgHwZXeIElRHIIVLQe9QZKiEgQ9Wkp6gyRFOwg2vscrL1w0kv8TMtIYJC/KQXBDS1djkLxoqucVUijSH6RUtKZlpx6kXhTS8rVXKLqlJaUepF6UpOVaPUi9qErLncagmdeiPi2vGoOmHos2tIlpDILHojtautAZ5LEoS8tveoM8FbX6tNThSYPngLeikP9DB154DngpEq/RhjeFEc8A/0UHeDSN0D/4L1rBq0q92qdP8F00HkDNgqfAd9HvgM4i+C6KQmsR/BZ1Aa1F8Fv0B/QWwWdRrgC9RfBZNAD0FsFvETQX4bMV4bMV4bMV4bMV4bMV4bMV4bMV4ZMVtSHxyo8pKsLd/IkfU5SEm1iKFqNFy0c4VZpP5AcVNeEU2pE0XXQ3JsluAsdazRwtBosGq/19tIVjqyeSxovk7kl+pqIH8nMVxen01JxRlIQxT3So3jinyBqm8NjyvgI4ihYwpU9RceM6aaswpUO79l0FEIqMB73SMl4UZNvIAsak33KSefl+tIY5t22SnL2IOWJREia1Qvf3vRZcPE74r9QAn0TlNvvUiEcRCAQCgUAgEAgEdPgLbm7XQrhD8bcAAAAASUVORK5CYII=";
    public static final int mainAssetsColor = Color.parseColor("#B4FFFFFF");
    public static final int shadowColor = Color.parseColor("#5c000000");
    public static final int backgroundColor = Color.parseColor("#52000000");

    static {
        IabElementStyle iabElementStyle = new IabElementStyle();
        defCloseStyle = iabElementStyle;
        iabElementStyle.setHorizontalPosition(5);
        iabElementStyle.setVerticalPosition(48);
        Float valueOf = Float.valueOf(2.0f);
        iabElementStyle.setStrokeWidth(valueOf);
        iabElementStyle.setStyle("cross");
        iabElementStyle.setMargin(8, 8, 8, 8);
        Float valueOf2 = Float.valueOf(30.0f);
        iabElementStyle.setWidth(valueOf2);
        iabElementStyle.setHeight(valueOf2);
        Float valueOf3 = Float.valueOf(3.0f);
        iabElementStyle.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle2 = new IabElementStyle();
        defSkipStyle = iabElementStyle2;
        iabElementStyle2.setHorizontalPosition(5);
        iabElementStyle2.setVerticalPosition(48);
        iabElementStyle2.setStrokeWidth(valueOf);
        iabElementStyle2.setStyle("skip");
        iabElementStyle2.setMargin(8, 8, 8, 8);
        iabElementStyle2.setWidth(valueOf2);
        iabElementStyle2.setHeight(valueOf2);
        iabElementStyle2.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle3 = new IabElementStyle();
        defCountDownStyle = iabElementStyle3;
        iabElementStyle3.setHorizontalPosition(5);
        iabElementStyle3.setVerticalPosition(48);
        iabElementStyle3.setStrokeWidth(valueOf);
        iabElementStyle3.setStyle("circular");
        iabElementStyle3.setMargin(8, 8, 8, 8);
        iabElementStyle3.setWidth(valueOf2);
        iabElementStyle3.setHeight(valueOf2);
        iabElementStyle3.setFontStyle(1);
        iabElementStyle3.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle4 = new IabElementStyle();
        defTextCountDownStyle = iabElementStyle4;
        iabElementStyle4.setHorizontalPosition(5);
        iabElementStyle4.setVerticalPosition(48);
        Float valueOf4 = Float.valueOf(16.0f);
        iabElementStyle4.setFontSize(valueOf4);
        iabElementStyle4.setStrokeWidth(valueOf);
        iabElementStyle4.setPadding(12, 2, 12, 2);
        iabElementStyle4.setContent("%1.0f%");
        iabElementStyle4.setStyle("text");
        iabElementStyle4.setMargin(8, 8, 8, 8);
        iabElementStyle4.setFontStyle(1);
        iabElementStyle4.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle5 = new IabElementStyle();
        defMuteStyle = iabElementStyle5;
        iabElementStyle5.setHorizontalPosition(3);
        iabElementStyle5.setVerticalPosition(48);
        iabElementStyle5.setStrokeWidth(valueOf);
        iabElementStyle5.setMargin(8, 8, 8, 8);
        iabElementStyle5.setWidth(valueOf2);
        iabElementStyle5.setHeight(valueOf2);
        iabElementStyle5.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle6 = new IabElementStyle();
        defRepeatStyle = iabElementStyle6;
        iabElementStyle6.setHorizontalPosition(17);
        iabElementStyle6.setVerticalPosition(48);
        iabElementStyle6.setStrokeWidth(valueOf);
        iabElementStyle6.setMargin(8, 8, 8, 8);
        iabElementStyle6.setWidth(valueOf2);
        iabElementStyle6.setHeight(valueOf2);
        iabElementStyle6.setVisible(Boolean.FALSE);
        iabElementStyle6.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle7 = new IabElementStyle();
        defLinearProgressStyle = iabElementStyle7;
        iabElementStyle7.setHorizontalPosition(17);
        iabElementStyle7.setVerticalPosition(80);
        iabElementStyle7.setFillColor(0);
        iabElementStyle7.setStrokeWidth(valueOf3);
        iabElementStyle7.setWidth(-1);
        iabElementStyle7.setHeight(3);
        iabElementStyle7.setStyle("linear");
        iabElementStyle7.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle8 = new IabElementStyle();
        defTextProgressStyle = iabElementStyle8;
        iabElementStyle8.setHorizontalPosition(17);
        iabElementStyle8.setVerticalPosition(80);
        iabElementStyle8.setFontSize(valueOf4);
        iabElementStyle8.setStrokeWidth(valueOf);
        iabElementStyle8.setPadding(12, 2, 12, 2);
        iabElementStyle8.setContent("%1.0f%");
        iabElementStyle8.setStyle("text");
        iabElementStyle8.setMargin(3, 3, 3, 3);
        iabElementStyle8.setFontStyle(1);
        iabElementStyle8.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle9 = new IabElementStyle();
        defCountDownProgressStyle = iabElementStyle9;
        iabElementStyle9.setHorizontalPosition(17);
        iabElementStyle9.setVerticalPosition(80);
        iabElementStyle9.setStrokeWidth(valueOf);
        iabElementStyle9.setOutlined(Boolean.TRUE);
        iabElementStyle9.setStyle("circular");
        iabElementStyle9.setMargin(8, 8, 8, 8);
        iabElementStyle9.setWidth(valueOf2);
        iabElementStyle9.setHeight(valueOf2);
        iabElementStyle9.setFontStyle(1);
        iabElementStyle9.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle10 = new IabElementStyle();
        defCtaStyle = iabElementStyle10;
        iabElementStyle10.setHorizontalPosition(5);
        iabElementStyle10.setVerticalPosition(80);
        iabElementStyle10.setFontSize(valueOf4);
        iabElementStyle10.setStrokeWidth(valueOf);
        iabElementStyle10.setPadding(16, 6, 16, 6);
        iabElementStyle10.setStyle("text");
        iabElementStyle10.setMargin(3, 3, 3, 3);
        iabElementStyle10.setFontStyle(1);
        iabElementStyle10.setHideAfter(valueOf3);
        IabElementStyle iabElementStyle11 = new IabElementStyle();
        defBannerStyle = iabElementStyle11;
        iabElementStyle11.setHorizontalPosition(17);
        iabElementStyle11.setVerticalPosition(80);
        iabElementStyle11.setFillColor(0);
        iabElementStyle11.setMargin(3, 3, 3, 3);
        IabElementStyle iabElementStyle12 = new IabElementStyle(iabElementStyle11);
        defInlineBannerStyle = iabElementStyle12;
        iabElementStyle12.setMargin(0, 0, 0, 0);
        IabElementStyle iabElementStyle13 = new IabElementStyle();
        defLoadingStyle = iabElementStyle13;
        iabElementStyle13.setHorizontalPosition(1);
        iabElementStyle13.setVerticalPosition(16);
        iabElementStyle13.setPadding(8, 8, 8, 8);
        iabElementStyle13.setStrokeWidth(valueOf3);
        iabElementStyle13.setWidth(48);
        iabElementStyle13.setHeight(48);
        IabElementStyle iabElementStyle14 = new IabElementStyle();
        defVideoStyle = iabElementStyle14;
        iabElementStyle14.setHorizontalPosition(3);
        iabElementStyle14.setVerticalPosition(48);
        iabElementStyle14.setFillColor(Integer.valueOf((int) ViewCompat.MEASURED_STATE_MASK));
        iabElementStyle14.setStyle("fullscreen");
    }

    public static Bitmap getBitmapFromBase64(String str) {
        byte[] decode = Base64.decode(str, 0);
        return BitmapFactory.decodeByteArray(decode, 0, decode.length);
    }

    public static IabElementStyle resolveDefCloseStyle(Context context, IabElementStyle iabElementStyle) {
        if (iabElementStyle == null || !("crossfill".equals(iabElementStyle.getStyle()) || "skipfill".equals(iabElementStyle.getStyle()))) {
            return defCloseStyle;
        }
        IabElementStyle iabElementStyle2 = new IabElementStyle();
        iabElementStyle2.setOutlined(Boolean.TRUE);
        return defCloseStyle.copyWith(iabElementStyle2);
    }
}
