package org.apache.ldap.server.schema.bootstrap;

import com.onesignal.NotificationBundleProcessor;
import java.util.ArrayList;
import javax.naming.NamingException;
import org.apache.ldap.server.jndi.JavaLdapSupport;
import org.apache.ldap.server.schema.bootstrap.AbstractBootstrapProducer;
/* loaded from: classes3.dex */
public class CoreObjectClassProducer extends AbstractBootstrapProducer {
    public CoreObjectClassProducer() {
        super(ProducerTypeEnum.OBJECT_CLASS_PRODUCER);
    }

    @Override // org.apache.ldap.server.schema.bootstrap.BootstrapProducer
    public void produce(BootstrapRegistries bootstrapRegistries, ProducerCallback producerCallback) throws NamingException {
        ArrayList arrayList = new ArrayList();
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass = AbstractBootstrapProducer.newObjectClass("2.5.6.14", bootstrapRegistries);
        newObjectClass.setObsolete(false);
        newObjectClass.setDescription("RFC2256: a device");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("serialNumber");
        arrayList.add("seeAlso");
        arrayList.add("owner");
        arrayList.add("ou");
        arrayList.add(NotificationBundleProcessor.PUSH_MINIFIED_BUTTONS_LIST);
        arrayList.add("l");
        arrayList.add("description");
        newObjectClass.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("device");
        newObjectClass.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.14", newObjectClass);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass2 = AbstractBootstrapProducer.newObjectClass("2.5.6.8", bootstrapRegistries);
        newObjectClass2.setObsolete(false);
        newObjectClass2.setDescription("RFC2256: an organizational role");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass2.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass2.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("x121Address");
        arrayList.add("registeredAddress");
        arrayList.add("destinationIndicator");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("telexNumber");
        arrayList.add("teletexTerminalIdentifier");
        arrayList.add("telephoneNumber");
        arrayList.add("internationaliSDNNumber");
        arrayList.add("facsimileTelephoneNumber");
        arrayList.add("seeAlso");
        arrayList.add("roleOccupant");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("street");
        arrayList.add("postOfficeBox");
        arrayList.add("postalCode");
        arrayList.add("postalAddress");
        arrayList.add("physicalDeliveryOfficeName");
        arrayList.add("ou");
        arrayList.add("st");
        arrayList.add("l");
        arrayList.add("description");
        newObjectClass2.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("organizationalRole");
        newObjectClass2.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.8", newObjectClass2);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass3 = AbstractBootstrapProducer.newObjectClass("2.5.6.17", bootstrapRegistries);
        newObjectClass3.setObsolete(false);
        newObjectClass3.setDescription("RFC2256: a group of unique names (DN and Unique Identifier)");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass3.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("uniqueMember");
        arrayList.add("cn");
        newObjectClass3.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("businessCategory");
        arrayList.add("seeAlso");
        arrayList.add("owner");
        arrayList.add("ou");
        arrayList.add(NotificationBundleProcessor.PUSH_MINIFIED_BUTTONS_LIST);
        arrayList.add("description");
        newObjectClass3.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("groupOfUniqueNames");
        newObjectClass3.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.17", newObjectClass3);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass4 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.19", bootstrapRegistries);
        newObjectClass4.setObsolete(false);
        newObjectClass4.setDescription("RFC1274: simple security object");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass4.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userPassword");
        newObjectClass4.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass4.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("simpleSecurityObject");
        newObjectClass4.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.19", newObjectClass4);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass5 = AbstractBootstrapProducer.newObjectClass("2.5.6.16.2", bootstrapRegistries);
        newObjectClass5.setObsolete(false);
        arrayList.clear();
        arrayList.add("certificationAuthority");
        newObjectClass5.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass5.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("deltaRevocationList");
        newObjectClass5.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("certificationAuthority-V2");
        newObjectClass5.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.16.2", newObjectClass5);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass6 = AbstractBootstrapProducer.newObjectClass("2.5.6.22", bootstrapRegistries);
        newObjectClass6.setObsolete(false);
        newObjectClass6.setDescription("RFC2587: PKI certificate authority");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass6.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass6.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("authorityRevocationList");
        arrayList.add("certificateRevocationList");
        arrayList.add("cACertificate");
        arrayList.add("crossCertificatePair");
        newObjectClass6.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("pkiCA");
        newObjectClass6.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.22", newObjectClass6);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass7 = AbstractBootstrapProducer.newObjectClass("2.5.6.7", bootstrapRegistries);
        newObjectClass7.setObsolete(false);
        newObjectClass7.setDescription("RFC2256: an organizational person");
        arrayList.clear();
        arrayList.add("person");
        newObjectClass7.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass7.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("title");
        arrayList.add("x121Address");
        arrayList.add("registeredAddress");
        arrayList.add("destinationIndicator");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("telexNumber");
        arrayList.add("teletexTerminalIdentifier");
        arrayList.add("telephoneNumber");
        arrayList.add("internationaliSDNNumber");
        arrayList.add("facsimileTelephoneNumber");
        arrayList.add("street");
        arrayList.add("postOfficeBox");
        arrayList.add("postalCode");
        arrayList.add("postalAddress");
        arrayList.add("physicalDeliveryOfficeName");
        arrayList.add("ou");
        arrayList.add("st");
        arrayList.add("l");
        newObjectClass7.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("organizationalPerson");
        newObjectClass7.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.7", newObjectClass7);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass8 = AbstractBootstrapProducer.newObjectClass("2.5.6.16", bootstrapRegistries);
        newObjectClass8.setObsolete(false);
        newObjectClass8.setDescription("RFC2256: a certificate authority");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass8.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("authorityRevocationList");
        arrayList.add("certificateRevocationList");
        arrayList.add("cACertificate");
        newObjectClass8.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("crossCertificatePair");
        newObjectClass8.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("certificationAuthority");
        newObjectClass8.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.16", newObjectClass8);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass9 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.1466.344", bootstrapRegistries);
        newObjectClass9.setObsolete(false);
        newObjectClass9.setDescription("RFC2247: domain component object");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass9.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dc");
        newObjectClass9.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass9.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dcObject");
        newObjectClass9.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.1466.344", newObjectClass9);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass10 = AbstractBootstrapProducer.newObjectClass("2.5.6.6", bootstrapRegistries);
        newObjectClass10.setObsolete(false);
        newObjectClass10.setDescription("RFC2256: a person");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass10.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sn");
        arrayList.add("cn");
        newObjectClass10.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userPassword");
        arrayList.add("telephoneNumber");
        arrayList.add("seeAlso");
        arrayList.add("description");
        newObjectClass10.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("person");
        newObjectClass10.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.6", newObjectClass10);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass11 = AbstractBootstrapProducer.newObjectClass("2.5.6.4", bootstrapRegistries);
        newObjectClass11.setObsolete(false);
        newObjectClass11.setDescription("RFC2256: an organization");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass11.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add(NotificationBundleProcessor.PUSH_MINIFIED_BUTTONS_LIST);
        newObjectClass11.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userPassword");
        arrayList.add("searchGuide");
        arrayList.add("seeAlso");
        arrayList.add("businessCategory");
        arrayList.add("x121Address");
        arrayList.add("registeredAddress");
        arrayList.add("destinationIndicator");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("telexNumber");
        arrayList.add("teletexTerminalIdentifier");
        arrayList.add("telephoneNumber");
        arrayList.add("internationaliSDNNumber");
        arrayList.add("facsimileTelephoneNumber");
        arrayList.add("street");
        arrayList.add("postOfficeBox");
        arrayList.add("postalCode");
        arrayList.add("postalAddress");
        arrayList.add("physicalDeliveryOfficeName");
        arrayList.add("st");
        arrayList.add("l");
        arrayList.add("description");
        newObjectClass11.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("organization");
        newObjectClass11.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.4", newObjectClass11);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass12 = AbstractBootstrapProducer.newObjectClass("2.5.6.19", bootstrapRegistries);
        newObjectClass12.setObsolete(false);
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass12.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass12.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("certificateRevocationList");
        arrayList.add("authorityRevocationList");
        arrayList.add("deltaRevocationList");
        newObjectClass12.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cRLDistributionPoint");
        newObjectClass12.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.19", newObjectClass12);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass13 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.250.3.15", bootstrapRegistries);
        newObjectClass13.setObsolete(false);
        newObjectClass13.setDescription("RFC2079: object that contains the URI attribute type");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass13.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass13.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("labeledURI");
        newObjectClass13.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("labeledURIObject");
        newObjectClass13.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.250.3.15", newObjectClass13);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass14 = AbstractBootstrapProducer.newObjectClass("2.5.6.23", bootstrapRegistries);
        newObjectClass14.setObsolete(false);
        newObjectClass14.setDescription("RFC2587: PKI user");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass14.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass14.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("deltaRevocationList");
        newObjectClass14.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("deltaCRL");
        newObjectClass14.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.23", newObjectClass14);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass15 = AbstractBootstrapProducer.newObjectClass("2.5.6.9", bootstrapRegistries);
        newObjectClass15.setObsolete(false);
        newObjectClass15.setDescription("RFC2256: a group of names (DNs)");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass15.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("member");
        arrayList.add("cn");
        newObjectClass15.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("businessCategory");
        arrayList.add("seeAlso");
        arrayList.add("owner");
        arrayList.add("ou");
        arrayList.add(NotificationBundleProcessor.PUSH_MINIFIED_BUTTONS_LIST);
        arrayList.add("description");
        newObjectClass15.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("groupOfNames");
        newObjectClass15.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.9", newObjectClass15);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass16 = AbstractBootstrapProducer.newObjectClass("2.5.6.13", bootstrapRegistries);
        newObjectClass16.setObsolete(false);
        newObjectClass16.setDescription("RFC2256: a directory system agent (a server)");
        arrayList.clear();
        arrayList.add("applicationEntity");
        newObjectClass16.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass16.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("knowledgeInformation");
        newObjectClass16.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dSA");
        newObjectClass16.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.13", newObjectClass16);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass17 = AbstractBootstrapProducer.newObjectClass("2.5.6.2", bootstrapRegistries);
        newObjectClass17.setObsolete(false);
        newObjectClass17.setDescription("RFC2256: a country");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass17.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("c");
        newObjectClass17.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("searchGuide");
        arrayList.add("description");
        newObjectClass17.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("country");
        newObjectClass17.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.2", newObjectClass17);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass18 = AbstractBootstrapProducer.newObjectClass("2.5.6.11", bootstrapRegistries);
        newObjectClass18.setObsolete(false);
        newObjectClass18.setDescription("RFC2256: an application process");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass18.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass18.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("seeAlso");
        arrayList.add("ou");
        arrayList.add("l");
        arrayList.add("description");
        newObjectClass18.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("applicationProcess");
        newObjectClass18.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.11", newObjectClass18);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass19 = AbstractBootstrapProducer.newObjectClass("2.5.6.21", bootstrapRegistries);
        newObjectClass19.setObsolete(false);
        newObjectClass19.setDescription("RFC2587: a PKI user");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass19.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass19.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userCertificate");
        newObjectClass19.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("pkiUser");
        newObjectClass19.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.21", newObjectClass19);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass20 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.3.1", bootstrapRegistries);
        newObjectClass20.setObsolete(false);
        newObjectClass20.setDescription("RFC2377: uid object");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass20.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("uid");
        newObjectClass20.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass20.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("uidObject");
        newObjectClass20.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.3.1", newObjectClass20);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass21 = AbstractBootstrapProducer.newObjectClass("2.5.6.3", bootstrapRegistries);
        newObjectClass21.setObsolete(false);
        newObjectClass21.setDescription("RFC2256: a locality");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass21.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass21.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("street");
        arrayList.add("seeAlso");
        arrayList.add("searchGuide");
        arrayList.add("st");
        arrayList.add("l");
        arrayList.add("description");
        newObjectClass21.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("locality");
        newObjectClass21.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.3", newObjectClass21);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass22 = AbstractBootstrapProducer.newObjectClass("2.5.6.12", bootstrapRegistries);
        newObjectClass22.setObsolete(false);
        newObjectClass22.setDescription("RFC2256: an application entity");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass22.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("presentationAddress");
        arrayList.add("cn");
        newObjectClass22.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("supportedApplicationContext");
        arrayList.add("seeAlso");
        arrayList.add("ou");
        arrayList.add(NotificationBundleProcessor.PUSH_MINIFIED_BUTTONS_LIST);
        arrayList.add("l");
        arrayList.add("description");
        newObjectClass22.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("applicationEntity");
        newObjectClass22.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.12", newObjectClass22);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass23 = AbstractBootstrapProducer.newObjectClass("2.5.6.20", bootstrapRegistries);
        newObjectClass23.setObsolete(false);
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass23.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dmdName");
        newObjectClass23.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userPassword");
        arrayList.add("searchGuide");
        arrayList.add("seeAlso");
        arrayList.add("businessCategory");
        arrayList.add("x121Address");
        arrayList.add("registeredAddress");
        arrayList.add("destinationIndicator");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("telexNumber");
        arrayList.add("teletexTerminalIdentifier");
        arrayList.add("telephoneNumber");
        arrayList.add("internationaliSDNNumber");
        arrayList.add("facsimileTelephoneNumber");
        arrayList.add("street");
        arrayList.add("postOfficeBox");
        arrayList.add("postalCode");
        arrayList.add("postalAddress");
        arrayList.add("physicalDeliveryOfficeName");
        arrayList.add("st");
        arrayList.add("l");
        arrayList.add("description");
        newObjectClass23.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dmd");
        newObjectClass23.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.20", newObjectClass23);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass24 = AbstractBootstrapProducer.newObjectClass("2.5.6.15", bootstrapRegistries);
        newObjectClass24.setObsolete(false);
        newObjectClass24.setDescription("RFC2256: a strong authentication user");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass24.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userCertificate");
        newObjectClass24.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass24.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("strongAuthenticationUser");
        newObjectClass24.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.15", newObjectClass24);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass25 = AbstractBootstrapProducer.newObjectClass("2.5.6.5", bootstrapRegistries);
        newObjectClass25.setObsolete(false);
        newObjectClass25.setDescription("RFC2256: an organizational unit");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass25.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("ou");
        newObjectClass25.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userPassword");
        arrayList.add("searchGuide");
        arrayList.add("seeAlso");
        arrayList.add("businessCategory");
        arrayList.add("x121Address");
        arrayList.add("registeredAddress");
        arrayList.add("destinationIndicator");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("telexNumber");
        arrayList.add("teletexTerminalIdentifier");
        arrayList.add("telephoneNumber");
        arrayList.add("internationaliSDNNumber");
        arrayList.add("facsimileTelephoneNumber");
        arrayList.add("street");
        arrayList.add("postOfficeBox");
        arrayList.add("postalCode");
        arrayList.add("postalAddress");
        arrayList.add("physicalDeliveryOfficeName");
        arrayList.add("st");
        arrayList.add("l");
        arrayList.add("description");
        newObjectClass25.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("organizationalUnit");
        newObjectClass25.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.5", newObjectClass25);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass26 = AbstractBootstrapProducer.newObjectClass("2.5.6.10", bootstrapRegistries);
        newObjectClass26.setObsolete(false);
        newObjectClass26.setDescription("RFC2256: an residential person");
        arrayList.clear();
        arrayList.add("person");
        newObjectClass26.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("l");
        newObjectClass26.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("businessCategory");
        arrayList.add("x121Address");
        arrayList.add("registeredAddress");
        arrayList.add("destinationIndicator");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("telexNumber");
        arrayList.add("teletexTerminalIdentifier");
        arrayList.add("telephoneNumber");
        arrayList.add("internationaliSDNNumber");
        arrayList.add("facsimileTelephoneNumber");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("street");
        arrayList.add("postOfficeBox");
        arrayList.add("postalCode");
        arrayList.add("postalAddress");
        arrayList.add("physicalDeliveryOfficeName");
        arrayList.add("st");
        arrayList.add("l");
        newObjectClass26.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("residentialPerson");
        newObjectClass26.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.10", newObjectClass26);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass27 = AbstractBootstrapProducer.newObjectClass("2.5.6.18", bootstrapRegistries);
        newObjectClass27.setObsolete(false);
        newObjectClass27.setDescription("RFC2256: a user security information");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass27.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass27.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("supportedAlgorithms");
        newObjectClass27.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userSecurityInformation");
        newObjectClass27.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.6.18", newObjectClass27);
    }
}
