package org.apache.ldap.server.schema.bootstrap;

import com.onesignal.NotificationBundleProcessor;
import java.util.ArrayList;
import javax.naming.NamingException;
import org.apache.ldap.common.schema.UsageEnum;
import org.apache.ldap.server.schema.bootstrap.AbstractBootstrapProducer;
/* loaded from: classes3.dex */
public class CoreAttributeTypeProducer extends AbstractBootstrapProducer {
    public CoreAttributeTypeProducer() {
        super(ProducerTypeEnum.ATTRIBUTE_TYPE_PRODUCER);
    }

    @Override // org.apache.ldap.server.schema.bootstrap.BootstrapProducer
    public void produce(BootstrapRegistries bootstrapRegistries, ProducerCallback producerCallback) throws NamingException {
        ArrayList arrayList = new ArrayList();
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType = AbstractBootstrapProducer.newAttributeType("2.5.4.6", bootstrapRegistries);
        newAttributeType.setDescription("RFC2256: ISO-3166 country 2-letter code");
        newAttributeType.setCanUserModify(true);
        newAttributeType.setSingleValue(true);
        newAttributeType.setCollective(false);
        newAttributeType.setObsolete(false);
        newAttributeType.setLength(-1);
        newAttributeType.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("c");
        arrayList.add("countryName");
        newAttributeType.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.6", newAttributeType);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType2 = AbstractBootstrapProducer.newAttributeType("2.5.4.43", bootstrapRegistries);
        newAttributeType2.setDescription("RFC2256: initials of some or all of names, but not the surname(s).");
        newAttributeType2.setCanUserModify(true);
        newAttributeType2.setSingleValue(false);
        newAttributeType2.setCollective(false);
        newAttributeType2.setObsolete(false);
        newAttributeType2.setLength(-1);
        newAttributeType2.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType2.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("initials");
        newAttributeType2.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.43", newAttributeType2);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType3 = AbstractBootstrapProducer.newAttributeType("2.5.4.21", bootstrapRegistries);
        newAttributeType3.setDescription("RFC2256: Telex Number");
        newAttributeType3.setCanUserModify(true);
        newAttributeType3.setSingleValue(false);
        newAttributeType3.setCollective(false);
        newAttributeType3.setObsolete(false);
        newAttributeType3.setLength(-1);
        newAttributeType3.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType3.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.52");
        arrayList.clear();
        arrayList.add("telexNumber");
        newAttributeType3.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.21", newAttributeType3);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType4 = AbstractBootstrapProducer.newAttributeType("2.5.4.9", bootstrapRegistries);
        newAttributeType4.setDescription("RFC2256: street address of this object");
        newAttributeType4.setCanUserModify(true);
        newAttributeType4.setSingleValue(false);
        newAttributeType4.setCollective(false);
        newAttributeType4.setObsolete(false);
        newAttributeType4.setLength(128);
        newAttributeType4.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType4.setEqualityId("caseIgnoreMatch");
        newAttributeType4.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType4.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("street");
        arrayList.add("streetAddress");
        newAttributeType4.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.9", newAttributeType4);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType5 = AbstractBootstrapProducer.newAttributeType("1.2.840.113549.1.9.1", bootstrapRegistries);
        newAttributeType5.setDescription("RFC2459: legacy attribute for email addresses in DNs");
        newAttributeType5.setCanUserModify(true);
        newAttributeType5.setSingleValue(false);
        newAttributeType5.setCollective(false);
        newAttributeType5.setObsolete(false);
        newAttributeType5.setLength(128);
        newAttributeType5.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType5.setEqualityId("caseIgnoreIA5Match");
        newAttributeType5.setSubstrId("caseIgnoreIA5SubstringsMatch");
        newAttributeType5.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("email");
        arrayList.add("emailAddress");
        arrayList.add("pkcs9email");
        newAttributeType5.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.2.840.113549.1.9.1", newAttributeType5);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType6 = AbstractBootstrapProducer.newAttributeType("2.5.4.26", bootstrapRegistries);
        newAttributeType6.setDescription("RFC2256: registered postal address");
        newAttributeType6.setCanUserModify(true);
        newAttributeType6.setSingleValue(false);
        newAttributeType6.setCollective(false);
        newAttributeType6.setObsolete(false);
        newAttributeType6.setLength(-1);
        newAttributeType6.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType6.setSuperiorId("postalAddress");
        newAttributeType6.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.41");
        arrayList.clear();
        arrayList.add("registeredAddress");
        newAttributeType6.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.26", newAttributeType6);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType7 = AbstractBootstrapProducer.newAttributeType("2.5.4.5", bootstrapRegistries);
        newAttributeType7.setDescription("RFC2256: serial number of the entity");
        newAttributeType7.setCanUserModify(true);
        newAttributeType7.setSingleValue(false);
        newAttributeType7.setCollective(false);
        newAttributeType7.setObsolete(false);
        newAttributeType7.setLength(64);
        newAttributeType7.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType7.setEqualityId("caseIgnoreMatch");
        newAttributeType7.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType7.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.44");
        arrayList.clear();
        arrayList.add("serialNumber");
        newAttributeType7.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.5", newAttributeType7);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType8 = AbstractBootstrapProducer.newAttributeType("2.5.4.44", bootstrapRegistries);
        newAttributeType8.setDescription("RFC2256: name qualifier indicating a generation");
        newAttributeType8.setCanUserModify(true);
        newAttributeType8.setSingleValue(false);
        newAttributeType8.setCollective(false);
        newAttributeType8.setObsolete(false);
        newAttributeType8.setLength(-1);
        newAttributeType8.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType8.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("generationQualifier");
        newAttributeType8.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.44", newAttributeType8);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType9 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.3", bootstrapRegistries);
        newAttributeType9.setDescription("RFC1274: RFC822 Mailbox");
        newAttributeType9.setCanUserModify(true);
        newAttributeType9.setSingleValue(false);
        newAttributeType9.setCollective(false);
        newAttributeType9.setObsolete(false);
        newAttributeType9.setLength(256);
        newAttributeType9.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType9.setEqualityId("caseIgnoreIA5Match");
        newAttributeType9.setSubstrId("caseIgnoreIA5SubstringsMatch");
        newAttributeType9.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("mail");
        arrayList.add("rfc822Mailbox");
        newAttributeType9.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.3", newAttributeType9);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType10 = AbstractBootstrapProducer.newAttributeType("2.5.4.18", bootstrapRegistries);
        newAttributeType10.setDescription("RFC2256: Post Office Box");
        newAttributeType10.setCanUserModify(true);
        newAttributeType10.setSingleValue(false);
        newAttributeType10.setCollective(false);
        newAttributeType10.setObsolete(false);
        newAttributeType10.setLength(40);
        newAttributeType10.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType10.setEqualityId("caseIgnoreMatch");
        newAttributeType10.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType10.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("postOfficeBox");
        newAttributeType10.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.18", newAttributeType10);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType11 = AbstractBootstrapProducer.newAttributeType("2.5.4.4", bootstrapRegistries);
        newAttributeType11.setDescription("RFC2256: last (family) name(s) for which the entity is known by");
        newAttributeType11.setCanUserModify(true);
        newAttributeType11.setSingleValue(false);
        newAttributeType11.setCollective(false);
        newAttributeType11.setObsolete(false);
        newAttributeType11.setLength(-1);
        newAttributeType11.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType11.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("sn");
        arrayList.add("surname");
        newAttributeType11.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.4", newAttributeType11);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType12 = AbstractBootstrapProducer.newAttributeType("2.5.4.40", bootstrapRegistries);
        newAttributeType12.setDescription("RFC2256: X.509 cross certificate pair, use ;binary");
        newAttributeType12.setCanUserModify(true);
        newAttributeType12.setSingleValue(false);
        newAttributeType12.setCollective(false);
        newAttributeType12.setObsolete(false);
        newAttributeType12.setLength(-1);
        newAttributeType12.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType12.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.10");
        arrayList.clear();
        arrayList.add("crossCertificatePair");
        newAttributeType12.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.40", newAttributeType12);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType13 = AbstractBootstrapProducer.newAttributeType("2.5.4.12", bootstrapRegistries);
        newAttributeType13.setDescription("RFC2256: title associated with the entity");
        newAttributeType13.setCanUserModify(true);
        newAttributeType13.setSingleValue(false);
        newAttributeType13.setCollective(false);
        newAttributeType13.setObsolete(false);
        newAttributeType13.setLength(-1);
        newAttributeType13.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType13.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("title");
        newAttributeType13.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.12", newAttributeType13);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType14 = AbstractBootstrapProducer.newAttributeType("2.5.4.13", bootstrapRegistries);
        newAttributeType14.setDescription("RFC2256: descriptive information");
        newAttributeType14.setCanUserModify(true);
        newAttributeType14.setSingleValue(false);
        newAttributeType14.setCollective(false);
        newAttributeType14.setObsolete(false);
        newAttributeType14.setLength(1024);
        newAttributeType14.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType14.setEqualityId("caseIgnoreMatch");
        newAttributeType14.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType14.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("description");
        newAttributeType14.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.13", newAttributeType14);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType15 = AbstractBootstrapProducer.newAttributeType("2.5.4.8", bootstrapRegistries);
        newAttributeType15.setDescription("RFC2256: state or province which this object resides in");
        newAttributeType15.setCanUserModify(true);
        newAttributeType15.setSingleValue(false);
        newAttributeType15.setCollective(false);
        newAttributeType15.setObsolete(false);
        newAttributeType15.setLength(-1);
        newAttributeType15.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType15.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("st");
        arrayList.add("stateOrProvinceName");
        newAttributeType15.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.8", newAttributeType15);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType16 = AbstractBootstrapProducer.newAttributeType("2.5.4.2", bootstrapRegistries);
        newAttributeType16.setDescription("RFC2256: knowledge information");
        newAttributeType16.setCanUserModify(true);
        newAttributeType16.setSingleValue(false);
        newAttributeType16.setCollective(false);
        newAttributeType16.setObsolete(false);
        newAttributeType16.setLength(32768);
        newAttributeType16.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType16.setEqualityId("caseIgnoreMatch");
        newAttributeType16.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("knowledgeInformation");
        newAttributeType16.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.2", newAttributeType16);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType17 = AbstractBootstrapProducer.newAttributeType("2.5.4.50", bootstrapRegistries);
        newAttributeType17.setDescription("RFC2256: unique member of a group");
        newAttributeType17.setCanUserModify(true);
        newAttributeType17.setSingleValue(false);
        newAttributeType17.setCollective(false);
        newAttributeType17.setObsolete(false);
        newAttributeType17.setLength(-1);
        newAttributeType17.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType17.setEqualityId("uniqueMemberMatch");
        newAttributeType17.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.34");
        arrayList.clear();
        arrayList.add("uniqueMember");
        newAttributeType17.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.50", newAttributeType17);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType18 = AbstractBootstrapProducer.newAttributeType("2.5.4.29", bootstrapRegistries);
        newAttributeType18.setDescription("RFC2256: presentation address");
        newAttributeType18.setCanUserModify(true);
        newAttributeType18.setSingleValue(true);
        newAttributeType18.setCollective(false);
        newAttributeType18.setObsolete(false);
        newAttributeType18.setLength(-1);
        newAttributeType18.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType18.setEqualityId("presentationAddressMatch");
        newAttributeType18.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.43");
        arrayList.clear();
        arrayList.add("presentationAddress");
        newAttributeType18.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.29", newAttributeType18);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType19 = AbstractBootstrapProducer.newAttributeType("2.5.4.36", bootstrapRegistries);
        newAttributeType19.setDescription("RFC2256: X.509 user certificate, use ;binary");
        newAttributeType19.setCanUserModify(true);
        newAttributeType19.setSingleValue(false);
        newAttributeType19.setCollective(false);
        newAttributeType19.setObsolete(false);
        newAttributeType19.setLength(-1);
        newAttributeType19.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType19.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.8");
        arrayList.clear();
        arrayList.add("userCertificate");
        newAttributeType19.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.36", newAttributeType19);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType20 = AbstractBootstrapProducer.newAttributeType("2.5.4.52", bootstrapRegistries);
        newAttributeType20.setDescription("RFC2256: supported algorithms");
        newAttributeType20.setCanUserModify(true);
        newAttributeType20.setSingleValue(false);
        newAttributeType20.setCollective(false);
        newAttributeType20.setObsolete(false);
        newAttributeType20.setLength(-1);
        newAttributeType20.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType20.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.49");
        arrayList.clear();
        arrayList.add("supportedAlgorithms");
        newAttributeType20.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.52", newAttributeType20);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType21 = AbstractBootstrapProducer.newAttributeType("2.5.4.17", bootstrapRegistries);
        newAttributeType21.setDescription("RFC2256: postal code");
        newAttributeType21.setCanUserModify(true);
        newAttributeType21.setSingleValue(false);
        newAttributeType21.setCollective(false);
        newAttributeType21.setObsolete(false);
        newAttributeType21.setLength(40);
        newAttributeType21.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType21.setEqualityId("caseIgnoreMatch");
        newAttributeType21.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType21.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("postalCode");
        newAttributeType21.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.17", newAttributeType21);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType22 = AbstractBootstrapProducer.newAttributeType("2.5.4.28", bootstrapRegistries);
        newAttributeType22.setDescription("RFC2256: preferred delivery method");
        newAttributeType22.setCanUserModify(true);
        newAttributeType22.setSingleValue(true);
        newAttributeType22.setCollective(false);
        newAttributeType22.setObsolete(false);
        newAttributeType22.setLength(-1);
        newAttributeType22.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType22.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.14");
        arrayList.clear();
        arrayList.add("preferredDeliveryMethod");
        newAttributeType22.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.28", newAttributeType22);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType23 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.1", bootstrapRegistries);
        newAttributeType23.setDescription("RFC1274: user identifier");
        newAttributeType23.setCanUserModify(true);
        newAttributeType23.setSingleValue(false);
        newAttributeType23.setCollective(false);
        newAttributeType23.setObsolete(false);
        newAttributeType23.setLength(256);
        newAttributeType23.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType23.setEqualityId("caseIgnoreMatch");
        newAttributeType23.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType23.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("uid");
        arrayList.add("userid");
        newAttributeType23.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.1", newAttributeType23);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType24 = AbstractBootstrapProducer.newAttributeType("2.5.4.42", bootstrapRegistries);
        newAttributeType24.setDescription("RFC2256: first name(s) for which the entity is known by");
        newAttributeType24.setCanUserModify(true);
        newAttributeType24.setSingleValue(false);
        newAttributeType24.setCollective(false);
        newAttributeType24.setObsolete(false);
        newAttributeType24.setLength(-1);
        newAttributeType24.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType24.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("givenName");
        arrayList.add("gn");
        newAttributeType24.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.42", newAttributeType24);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType25 = AbstractBootstrapProducer.newAttributeType("2.5.4.30", bootstrapRegistries);
        newAttributeType25.setDescription("RFC2256: supported application context");
        newAttributeType25.setCanUserModify(true);
        newAttributeType25.setSingleValue(false);
        newAttributeType25.setCollective(false);
        newAttributeType25.setObsolete(false);
        newAttributeType25.setLength(-1);
        newAttributeType25.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType25.setEqualityId("objectIdentifierMatch");
        newAttributeType25.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.38");
        arrayList.clear();
        arrayList.add("supportedApplicationContext");
        newAttributeType25.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.30", newAttributeType25);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType26 = AbstractBootstrapProducer.newAttributeType("2.5.4.31", bootstrapRegistries);
        newAttributeType26.setDescription("RFC2256: member of a group");
        newAttributeType26.setCanUserModify(true);
        newAttributeType26.setSingleValue(false);
        newAttributeType26.setCollective(false);
        newAttributeType26.setObsolete(false);
        newAttributeType26.setLength(-1);
        newAttributeType26.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType26.setSuperiorId("distinguishedName");
        arrayList.clear();
        arrayList.add("member");
        newAttributeType26.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.31", newAttributeType26);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType27 = AbstractBootstrapProducer.newAttributeType("2.5.4.54", bootstrapRegistries);
        newAttributeType27.setDescription("RFC2256: name of DMD");
        newAttributeType27.setCanUserModify(true);
        newAttributeType27.setSingleValue(false);
        newAttributeType27.setCollective(false);
        newAttributeType27.setObsolete(false);
        newAttributeType27.setLength(-1);
        newAttributeType27.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType27.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("dmdName");
        newAttributeType27.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.54", newAttributeType27);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType28 = AbstractBootstrapProducer.newAttributeType("2.5.4.10", bootstrapRegistries);
        newAttributeType28.setDescription("RFC2256: organization this object belongs to");
        newAttributeType28.setCanUserModify(true);
        newAttributeType28.setSingleValue(false);
        newAttributeType28.setCollective(false);
        newAttributeType28.setObsolete(false);
        newAttributeType28.setLength(-1);
        newAttributeType28.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType28.setSuperiorId("name");
        arrayList.clear();
        arrayList.add(NotificationBundleProcessor.PUSH_MINIFIED_BUTTONS_LIST);
        arrayList.add("organizationName");
        newAttributeType28.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.10", newAttributeType28);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType29 = AbstractBootstrapProducer.newAttributeType("2.5.4.32", bootstrapRegistries);
        newAttributeType29.setDescription("RFC2256: owner (of the object)");
        newAttributeType29.setCanUserModify(true);
        newAttributeType29.setSingleValue(false);
        newAttributeType29.setCollective(false);
        newAttributeType29.setObsolete(false);
        newAttributeType29.setLength(-1);
        newAttributeType29.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType29.setSuperiorId("distinguishedName");
        arrayList.clear();
        arrayList.add("owner");
        newAttributeType29.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.32", newAttributeType29);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType30 = AbstractBootstrapProducer.newAttributeType("2.5.4.48", bootstrapRegistries);
        newAttributeType30.setDescription("RFC2256: protocol information");
        newAttributeType30.setCanUserModify(true);
        newAttributeType30.setSingleValue(false);
        newAttributeType30.setCollective(false);
        newAttributeType30.setObsolete(false);
        newAttributeType30.setLength(-1);
        newAttributeType30.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType30.setEqualityId("protocolInformationMatch");
        newAttributeType30.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.42");
        arrayList.clear();
        arrayList.add("protocolInformation");
        newAttributeType30.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.48", newAttributeType30);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType31 = AbstractBootstrapProducer.newAttributeType("2.5.4.19", bootstrapRegistries);
        newAttributeType31.setDescription("RFC2256: Physical Delivery Office Name");
        newAttributeType31.setCanUserModify(true);
        newAttributeType31.setSingleValue(false);
        newAttributeType31.setCollective(false);
        newAttributeType31.setObsolete(false);
        newAttributeType31.setLength(128);
        newAttributeType31.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType31.setEqualityId("caseIgnoreMatch");
        newAttributeType31.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType31.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("physicalDeliveryOfficeName");
        newAttributeType31.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.19", newAttributeType31);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType32 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.37", bootstrapRegistries);
        newAttributeType32.setDescription("RFC1274: domain associated with object");
        newAttributeType32.setCanUserModify(true);
        newAttributeType32.setSingleValue(false);
        newAttributeType32.setCollective(false);
        newAttributeType32.setObsolete(false);
        newAttributeType32.setLength(-1);
        newAttributeType32.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType32.setEqualityId("caseIgnoreIA5Match");
        newAttributeType32.setSubstrId("caseIgnoreIA5SubstringsMatch");
        newAttributeType32.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("associatedDomain");
        newAttributeType32.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.37", newAttributeType32);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType33 = AbstractBootstrapProducer.newAttributeType("2.5.4.51", bootstrapRegistries);
        newAttributeType33.setDescription("RFC2256: house identifier");
        newAttributeType33.setCanUserModify(true);
        newAttributeType33.setSingleValue(false);
        newAttributeType33.setCollective(false);
        newAttributeType33.setObsolete(false);
        newAttributeType33.setLength(32768);
        newAttributeType33.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType33.setEqualityId("caseIgnoreMatch");
        newAttributeType33.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType33.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("houseIdentifier");
        newAttributeType33.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.51", newAttributeType33);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType34 = AbstractBootstrapProducer.newAttributeType("2.5.4.22", bootstrapRegistries);
        newAttributeType34.setDescription("RFC2256: Teletex Terminal Identifier");
        newAttributeType34.setCanUserModify(true);
        newAttributeType34.setSingleValue(false);
        newAttributeType34.setCollective(false);
        newAttributeType34.setObsolete(false);
        newAttributeType34.setLength(-1);
        newAttributeType34.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType34.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.51");
        arrayList.clear();
        arrayList.add("teletexTerminalIdentifier");
        newAttributeType34.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.22", newAttributeType34);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType35 = AbstractBootstrapProducer.newAttributeType("2.5.4.25", bootstrapRegistries);
        newAttributeType35.setDescription("RFC2256: international ISDN number");
        newAttributeType35.setCanUserModify(true);
        newAttributeType35.setSingleValue(false);
        newAttributeType35.setCollective(false);
        newAttributeType35.setObsolete(false);
        newAttributeType35.setLength(16);
        newAttributeType35.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType35.setEqualityId("numericStringMatch");
        newAttributeType35.setSubstrId("numericStringSubstringsMatch");
        newAttributeType35.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.36");
        arrayList.clear();
        arrayList.add("internationaliSDNNumber");
        newAttributeType35.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.25", newAttributeType35);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType36 = AbstractBootstrapProducer.newAttributeType("2.5.4.34", bootstrapRegistries);
        newAttributeType36.setDescription("RFC2256: DN of related object");
        newAttributeType36.setCanUserModify(true);
        newAttributeType36.setSingleValue(false);
        newAttributeType36.setCollective(false);
        newAttributeType36.setObsolete(false);
        newAttributeType36.setLength(-1);
        newAttributeType36.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType36.setSuperiorId("distinguishedName");
        arrayList.clear();
        arrayList.add("seeAlso");
        newAttributeType36.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.34", newAttributeType36);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType37 = AbstractBootstrapProducer.newAttributeType("2.5.4.47", bootstrapRegistries);
        newAttributeType37.setDescription("RFC2256: enhanced search guide");
        newAttributeType37.setCanUserModify(true);
        newAttributeType37.setSingleValue(false);
        newAttributeType37.setCollective(false);
        newAttributeType37.setObsolete(false);
        newAttributeType37.setLength(-1);
        newAttributeType37.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType37.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.21");
        arrayList.clear();
        arrayList.add("enhancedSearchGuide");
        newAttributeType37.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.47", newAttributeType37);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType38 = AbstractBootstrapProducer.newAttributeType("2.5.4.24", bootstrapRegistries);
        newAttributeType38.setDescription("RFC2256: X.121 Address");
        newAttributeType38.setCanUserModify(true);
        newAttributeType38.setSingleValue(false);
        newAttributeType38.setCollective(false);
        newAttributeType38.setObsolete(false);
        newAttributeType38.setLength(15);
        newAttributeType38.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType38.setEqualityId("numericStringMatch");
        newAttributeType38.setSubstrId("numericStringSubstringsMatch");
        newAttributeType38.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.36");
        arrayList.clear();
        arrayList.add("x121Address");
        newAttributeType38.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.24", newAttributeType38);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType39 = AbstractBootstrapProducer.newAttributeType("2.5.4.7", bootstrapRegistries);
        newAttributeType39.setDescription("RFC2256: locality which this object resides in");
        newAttributeType39.setCanUserModify(true);
        newAttributeType39.setSingleValue(false);
        newAttributeType39.setCollective(false);
        newAttributeType39.setObsolete(false);
        newAttributeType39.setLength(-1);
        newAttributeType39.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType39.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("l");
        arrayList.add("localityName");
        newAttributeType39.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.7", newAttributeType39);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType40 = AbstractBootstrapProducer.newAttributeType("2.5.4.46", bootstrapRegistries);
        newAttributeType40.setDescription("RFC2256: DN qualifier");
        newAttributeType40.setCanUserModify(true);
        newAttributeType40.setSingleValue(false);
        newAttributeType40.setCollective(false);
        newAttributeType40.setObsolete(false);
        newAttributeType40.setLength(-1);
        newAttributeType40.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType40.setEqualityId("caseIgnoreMatch");
        newAttributeType40.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType40.setOrderingId("caseIgnoreOrderingMatch");
        newAttributeType40.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.44");
        arrayList.clear();
        arrayList.add("dnQualifier");
        newAttributeType40.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.46", newAttributeType40);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType41 = AbstractBootstrapProducer.newAttributeType("2.5.4.27", bootstrapRegistries);
        newAttributeType41.setDescription("RFC2256: destination indicator");
        newAttributeType41.setCanUserModify(true);
        newAttributeType41.setSingleValue(false);
        newAttributeType41.setCollective(false);
        newAttributeType41.setObsolete(false);
        newAttributeType41.setLength(128);
        newAttributeType41.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType41.setEqualityId("caseIgnoreMatch");
        newAttributeType41.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType41.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.44");
        arrayList.clear();
        arrayList.add("destinationIndicator");
        newAttributeType41.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.27", newAttributeType41);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType42 = AbstractBootstrapProducer.newAttributeType("2.5.4.16", bootstrapRegistries);
        newAttributeType42.setDescription("RFC2256: postal address");
        newAttributeType42.setCanUserModify(true);
        newAttributeType42.setSingleValue(false);
        newAttributeType42.setCollective(false);
        newAttributeType42.setObsolete(false);
        newAttributeType42.setLength(-1);
        newAttributeType42.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType42.setEqualityId("caseIgnoreListMatch");
        newAttributeType42.setSubstrId("caseIgnoreListSubstringsMatch");
        newAttributeType42.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.41");
        arrayList.clear();
        arrayList.add("postalAddress");
        newAttributeType42.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.16", newAttributeType42);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType43 = AbstractBootstrapProducer.newAttributeType("2.5.4.38", bootstrapRegistries);
        newAttributeType43.setDescription("RFC2256: X.509 authority revocation list, use ;binary");
        newAttributeType43.setCanUserModify(true);
        newAttributeType43.setSingleValue(false);
        newAttributeType43.setCollective(false);
        newAttributeType43.setObsolete(false);
        newAttributeType43.setLength(-1);
        newAttributeType43.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType43.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.9");
        arrayList.clear();
        arrayList.add("authorityRevocationList");
        newAttributeType43.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.38", newAttributeType43);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType44 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.25", bootstrapRegistries);
        newAttributeType44.setDescription("RFC1274/2247: domain component");
        newAttributeType44.setCanUserModify(true);
        newAttributeType44.setSingleValue(true);
        newAttributeType44.setCollective(false);
        newAttributeType44.setObsolete(false);
        newAttributeType44.setLength(-1);
        newAttributeType44.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType44.setEqualityId("caseIgnoreIA5Match");
        newAttributeType44.setSubstrId("caseIgnoreIA5SubstringsMatch");
        newAttributeType44.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("dc");
        arrayList.add("domainComponent");
        newAttributeType44.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.25", newAttributeType44);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType45 = AbstractBootstrapProducer.newAttributeType("2.5.4.37", bootstrapRegistries);
        newAttributeType45.setDescription("RFC2256: X.509 CA certificate, use ;binary");
        newAttributeType45.setCanUserModify(true);
        newAttributeType45.setSingleValue(false);
        newAttributeType45.setCollective(false);
        newAttributeType45.setObsolete(false);
        newAttributeType45.setLength(-1);
        newAttributeType45.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType45.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.8");
        arrayList.clear();
        arrayList.add("cACertificate");
        newAttributeType45.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.37", newAttributeType45);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType46 = AbstractBootstrapProducer.newAttributeType("2.5.4.15", bootstrapRegistries);
        newAttributeType46.setDescription("RFC2256: business category");
        newAttributeType46.setCanUserModify(true);
        newAttributeType46.setSingleValue(false);
        newAttributeType46.setCollective(false);
        newAttributeType46.setObsolete(false);
        newAttributeType46.setLength(128);
        newAttributeType46.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType46.setEqualityId("caseIgnoreMatch");
        newAttributeType46.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType46.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("businessCategory");
        newAttributeType46.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.15", newAttributeType46);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType47 = AbstractBootstrapProducer.newAttributeType("2.5.4.33", bootstrapRegistries);
        newAttributeType47.setDescription("RFC2256: occupant of role");
        newAttributeType47.setCanUserModify(true);
        newAttributeType47.setSingleValue(false);
        newAttributeType47.setCollective(false);
        newAttributeType47.setObsolete(false);
        newAttributeType47.setLength(-1);
        newAttributeType47.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType47.setSuperiorId("distinguishedName");
        arrayList.clear();
        arrayList.add("roleOccupant");
        newAttributeType47.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.33", newAttributeType47);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType48 = AbstractBootstrapProducer.newAttributeType("2.5.4.11", bootstrapRegistries);
        newAttributeType48.setDescription("RFC2256: organizational unit this object belongs to");
        newAttributeType48.setCanUserModify(true);
        newAttributeType48.setSingleValue(false);
        newAttributeType48.setCollective(false);
        newAttributeType48.setObsolete(false);
        newAttributeType48.setLength(-1);
        newAttributeType48.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType48.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("ou");
        arrayList.add("organizationalUnitName");
        newAttributeType48.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.11", newAttributeType48);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType49 = AbstractBootstrapProducer.newAttributeType("2.5.4.14", bootstrapRegistries);
        newAttributeType49.setDescription("RFC2256: search guide, obsoleted by enhancedSearchGuide");
        newAttributeType49.setCanUserModify(true);
        newAttributeType49.setSingleValue(false);
        newAttributeType49.setCollective(false);
        newAttributeType49.setObsolete(false);
        newAttributeType49.setLength(-1);
        newAttributeType49.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType49.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.25");
        arrayList.clear();
        arrayList.add("searchGuide");
        newAttributeType49.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.14", newAttributeType49);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType50 = AbstractBootstrapProducer.newAttributeType("2.5.4.23", bootstrapRegistries);
        newAttributeType50.setDescription("RFC2256: Facsimile (Fax) Telephone Number");
        newAttributeType50.setCanUserModify(true);
        newAttributeType50.setSingleValue(false);
        newAttributeType50.setCollective(false);
        newAttributeType50.setObsolete(false);
        newAttributeType50.setLength(-1);
        newAttributeType50.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType50.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.22");
        arrayList.clear();
        arrayList.add("facsimileTelephoneNumber");
        arrayList.add("fax");
        newAttributeType50.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.23", newAttributeType50);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType51 = AbstractBootstrapProducer.newAttributeType("2.5.4.45", bootstrapRegistries);
        newAttributeType51.setDescription("RFC2256: X.500 unique identifier");
        newAttributeType51.setCanUserModify(true);
        newAttributeType51.setSingleValue(false);
        newAttributeType51.setCollective(false);
        newAttributeType51.setObsolete(false);
        newAttributeType51.setLength(-1);
        newAttributeType51.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType51.setEqualityId("bitStringMatch");
        newAttributeType51.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.6");
        arrayList.clear();
        arrayList.add("x500UniqueIdentifier");
        newAttributeType51.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.45", newAttributeType51);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType52 = AbstractBootstrapProducer.newAttributeType("2.5.4.39", bootstrapRegistries);
        newAttributeType52.setDescription("RFC2256: X.509 certificate revocation list, use ;binary");
        newAttributeType52.setCanUserModify(true);
        newAttributeType52.setSingleValue(false);
        newAttributeType52.setCollective(false);
        newAttributeType52.setObsolete(false);
        newAttributeType52.setLength(-1);
        newAttributeType52.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType52.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.9");
        arrayList.clear();
        arrayList.add("certificateRevocationList");
        newAttributeType52.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.39", newAttributeType52);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType53 = AbstractBootstrapProducer.newAttributeType("2.5.4.53", bootstrapRegistries);
        newAttributeType53.setDescription("RFC2256: delta revocation list; use ;binary");
        newAttributeType53.setCanUserModify(true);
        newAttributeType53.setSingleValue(false);
        newAttributeType53.setCollective(false);
        newAttributeType53.setObsolete(false);
        newAttributeType53.setLength(-1);
        newAttributeType53.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType53.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.9");
        arrayList.clear();
        arrayList.add("deltaRevocationList");
        newAttributeType53.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.53", newAttributeType53);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType54 = AbstractBootstrapProducer.newAttributeType("2.5.4.20", bootstrapRegistries);
        newAttributeType54.setDescription("RFC2256: Telephone Number");
        newAttributeType54.setCanUserModify(true);
        newAttributeType54.setSingleValue(false);
        newAttributeType54.setCollective(false);
        newAttributeType54.setObsolete(false);
        newAttributeType54.setLength(32);
        newAttributeType54.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType54.setEqualityId("telephoneNumberMatch");
        newAttributeType54.setSubstrId("telephoneNumberSubstringsMatch");
        newAttributeType54.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.50");
        arrayList.clear();
        arrayList.add("telephoneNumber");
        newAttributeType54.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.20", newAttributeType54);
    }
}
