package org.apache.ldap.server.schema.bootstrap;

import java.util.ArrayList;
import javax.naming.NamingException;
import org.apache.ldap.common.schema.UsageEnum;
import org.apache.ldap.server.schema.bootstrap.AbstractBootstrapProducer;
/* loaded from: classes3.dex */
public class CosineAttributeTypeProducer extends AbstractBootstrapProducer {
    public CosineAttributeTypeProducer() {
        super(ProducerTypeEnum.ATTRIBUTE_TYPE_PRODUCER);
    }

    @Override // org.apache.ldap.server.schema.bootstrap.BootstrapProducer
    public void produce(BootstrapRegistries bootstrapRegistries, ProducerCallback producerCallback) throws NamingException {
        ArrayList arrayList = new ArrayList();
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.21", bootstrapRegistries);
        newAttributeType.setDescription("RFC1274: DN of secretary");
        newAttributeType.setCanUserModify(true);
        newAttributeType.setSingleValue(false);
        newAttributeType.setCollective(false);
        newAttributeType.setObsolete(false);
        newAttributeType.setLength(-1);
        newAttributeType.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType.setEqualityId("distinguishedNameMatch");
        newAttributeType.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("secretary");
        newAttributeType.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.21", newAttributeType);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType2 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.43", bootstrapRegistries);
        newAttributeType2.setDescription("RFC1274: friendly country name");
        newAttributeType2.setCanUserModify(true);
        newAttributeType2.setSingleValue(false);
        newAttributeType2.setCollective(false);
        newAttributeType2.setObsolete(false);
        newAttributeType2.setLength(-1);
        newAttributeType2.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType2.setEqualityId("caseIgnoreMatch");
        newAttributeType2.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType2.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("co");
        arrayList.add("friendlyCountryName");
        newAttributeType2.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.43", newAttributeType2);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType3 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.10", bootstrapRegistries);
        newAttributeType3.setDescription("RFC1274: DN of manager");
        newAttributeType3.setCanUserModify(true);
        newAttributeType3.setSingleValue(false);
        newAttributeType3.setCollective(false);
        newAttributeType3.setObsolete(false);
        newAttributeType3.setLength(-1);
        newAttributeType3.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType3.setEqualityId("distinguishedNameMatch");
        newAttributeType3.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("manager");
        newAttributeType3.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.10", newAttributeType3);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType4 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.2", bootstrapRegistries);
        newAttributeType4.setCanUserModify(true);
        newAttributeType4.setSingleValue(false);
        newAttributeType4.setCollective(false);
        newAttributeType4.setObsolete(false);
        newAttributeType4.setLength(256);
        newAttributeType4.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType4.setEqualityId("caseIgnoreMatch");
        newAttributeType4.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType4.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("textEncodedORAddress");
        newAttributeType4.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.2", newAttributeType4);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType5 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.52", bootstrapRegistries);
        newAttributeType5.setDescription("RFC1274: Subtree Maximun Quality");
        newAttributeType5.setCanUserModify(true);
        newAttributeType5.setSingleValue(true);
        newAttributeType5.setCollective(false);
        newAttributeType5.setObsolete(false);
        newAttributeType5.setLength(-1);
        newAttributeType5.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType5.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.13");
        arrayList.clear();
        arrayList.add("subtreeMaximumQuality");
        newAttributeType5.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.52", newAttributeType5);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType6 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.54", bootstrapRegistries);
        newAttributeType6.setDescription("RFC1274: DIT Redirect");
        newAttributeType6.setCanUserModify(true);
        newAttributeType6.setSingleValue(false);
        newAttributeType6.setCollective(false);
        newAttributeType6.setObsolete(false);
        newAttributeType6.setLength(-1);
        newAttributeType6.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType6.setEqualityId("distinguishedNameMatch");
        newAttributeType6.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("dITRedirect");
        newAttributeType6.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.54", newAttributeType6);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType7 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.9", bootstrapRegistries);
        newAttributeType7.setDescription("RFC1274: host computer");
        newAttributeType7.setCanUserModify(true);
        newAttributeType7.setSingleValue(false);
        newAttributeType7.setCollective(false);
        newAttributeType7.setObsolete(false);
        newAttributeType7.setLength(256);
        newAttributeType7.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType7.setEqualityId("caseIgnoreMatch");
        newAttributeType7.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType7.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("host");
        newAttributeType7.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.9", newAttributeType7);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType8 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.50", bootstrapRegistries);
        newAttributeType8.setDescription("RFC1274: Single Level Quality");
        newAttributeType8.setCanUserModify(true);
        newAttributeType8.setSingleValue(true);
        newAttributeType8.setCollective(false);
        newAttributeType8.setObsolete(false);
        newAttributeType8.setLength(-1);
        newAttributeType8.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType8.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.13");
        arrayList.clear();
        arrayList.add("singleLevelQuality");
        newAttributeType8.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.50", newAttributeType8);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType9 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.30", bootstrapRegistries);
        newAttributeType9.setCanUserModify(true);
        newAttributeType9.setSingleValue(false);
        newAttributeType9.setCollective(false);
        newAttributeType9.setObsolete(false);
        newAttributeType9.setLength(-1);
        newAttributeType9.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType9.setEqualityId("caseIgnoreIA5Match");
        newAttributeType9.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sOARecord");
        newAttributeType9.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.30", newAttributeType9);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType10 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.41", bootstrapRegistries);
        newAttributeType10.setDescription("RFC1274: mobile telephone number");
        newAttributeType10.setCanUserModify(true);
        newAttributeType10.setSingleValue(false);
        newAttributeType10.setCollective(false);
        newAttributeType10.setObsolete(false);
        newAttributeType10.setLength(-1);
        newAttributeType10.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType10.setEqualityId("telephoneNumberMatch");
        newAttributeType10.setSubstrId("telephoneNumberSubstringsMatch");
        newAttributeType10.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.50");
        arrayList.clear();
        arrayList.add("mobile");
        arrayList.add("mobileTelephoneNumber");
        newAttributeType10.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.41", newAttributeType10);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType11 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.29", bootstrapRegistries);
        newAttributeType11.setCanUserModify(true);
        newAttributeType11.setSingleValue(false);
        newAttributeType11.setCollective(false);
        newAttributeType11.setObsolete(false);
        newAttributeType11.setLength(-1);
        newAttributeType11.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType11.setEqualityId("caseIgnoreIA5Match");
        newAttributeType11.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("nSRecord");
        newAttributeType11.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.29", newAttributeType11);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType12 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.22", bootstrapRegistries);
        newAttributeType12.setCanUserModify(true);
        newAttributeType12.setSingleValue(false);
        newAttributeType12.setCollective(false);
        newAttributeType12.setObsolete(false);
        newAttributeType12.setLength(-1);
        newAttributeType12.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType12.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.39");
        arrayList.clear();
        arrayList.add("otherMailbox");
        newAttributeType12.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.22", newAttributeType12);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType13 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.44", bootstrapRegistries);
        newAttributeType13.setDescription("RFC1274: unique identifer");
        newAttributeType13.setCanUserModify(true);
        newAttributeType13.setSingleValue(false);
        newAttributeType13.setCollective(false);
        newAttributeType13.setObsolete(false);
        newAttributeType13.setLength(256);
        newAttributeType13.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType13.setEqualityId("caseIgnoreMatch");
        newAttributeType13.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("uniqueIdentifier");
        newAttributeType13.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.44", newAttributeType13);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType14 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.15", bootstrapRegistries);
        newAttributeType14.setDescription("RFC1274: location of document original");
        newAttributeType14.setCanUserModify(true);
        newAttributeType14.setSingleValue(false);
        newAttributeType14.setCollective(false);
        newAttributeType14.setObsolete(false);
        newAttributeType14.setLength(256);
        newAttributeType14.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType14.setEqualityId("caseIgnoreMatch");
        newAttributeType14.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType14.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("documentLocation");
        newAttributeType14.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.15", newAttributeType14);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType15 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.51", bootstrapRegistries);
        newAttributeType15.setDescription("RFC1274: Subtree Mininum Quality");
        newAttributeType15.setCanUserModify(true);
        newAttributeType15.setSingleValue(true);
        newAttributeType15.setCollective(false);
        newAttributeType15.setObsolete(false);
        newAttributeType15.setLength(-1);
        newAttributeType15.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType15.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.13");
        arrayList.clear();
        arrayList.add("subtreeMinimumQuality");
        newAttributeType15.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.51", newAttributeType15);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType16 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.49", bootstrapRegistries);
        newAttributeType16.setDescription("RFC1274: DSA Quality");
        newAttributeType16.setCanUserModify(true);
        newAttributeType16.setSingleValue(true);
        newAttributeType16.setCollective(false);
        newAttributeType16.setObsolete(false);
        newAttributeType16.setLength(-1);
        newAttributeType16.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType16.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.19");
        arrayList.clear();
        arrayList.add("dSAQuality");
        newAttributeType16.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.49", newAttributeType16);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType17 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.12", bootstrapRegistries);
        newAttributeType17.setDescription("RFC1274: title of document");
        newAttributeType17.setCanUserModify(true);
        newAttributeType17.setSingleValue(false);
        newAttributeType17.setCollective(false);
        newAttributeType17.setObsolete(false);
        newAttributeType17.setLength(256);
        newAttributeType17.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType17.setEqualityId("caseIgnoreMatch");
        newAttributeType17.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType17.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("documentTitle");
        newAttributeType17.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.12", newAttributeType17);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType18 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.40", bootstrapRegistries);
        newAttributeType18.setDescription("RFC1274: personal title");
        newAttributeType18.setCanUserModify(true);
        newAttributeType18.setSingleValue(false);
        newAttributeType18.setCollective(false);
        newAttributeType18.setObsolete(false);
        newAttributeType18.setLength(256);
        newAttributeType18.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType18.setEqualityId("caseIgnoreMatch");
        newAttributeType18.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType18.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("personalTitle");
        newAttributeType18.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.40", newAttributeType18);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType19 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.27", bootstrapRegistries);
        newAttributeType19.setCanUserModify(true);
        newAttributeType19.setSingleValue(false);
        newAttributeType19.setCollective(false);
        newAttributeType19.setObsolete(false);
        newAttributeType19.setLength(-1);
        newAttributeType19.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType19.setEqualityId("caseIgnoreIA5Match");
        newAttributeType19.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("mDRecord");
        newAttributeType19.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.27", newAttributeType19);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType20 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.8", bootstrapRegistries);
        newAttributeType20.setDescription("RFC1274: categorory of user");
        newAttributeType20.setCanUserModify(true);
        newAttributeType20.setSingleValue(false);
        newAttributeType20.setCollective(false);
        newAttributeType20.setObsolete(false);
        newAttributeType20.setLength(256);
        newAttributeType20.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType20.setEqualityId("caseIgnoreMatch");
        newAttributeType20.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType20.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("userClass");
        newAttributeType20.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.8", newAttributeType20);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType21 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.7", bootstrapRegistries);
        newAttributeType21.setDescription("RFC1274: photo (G3 fax)");
        newAttributeType21.setCanUserModify(true);
        newAttributeType21.setSingleValue(false);
        newAttributeType21.setCollective(false);
        newAttributeType21.setObsolete(false);
        newAttributeType21.setLength(25000);
        newAttributeType21.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType21.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.23");
        arrayList.clear();
        arrayList.add("photo");
        newAttributeType21.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.7", newAttributeType21);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType22 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.56", bootstrapRegistries);
        newAttributeType22.setDescription("RFC1274: publisher of document");
        newAttributeType22.setCanUserModify(true);
        newAttributeType22.setSingleValue(false);
        newAttributeType22.setCollective(false);
        newAttributeType22.setObsolete(false);
        newAttributeType22.setLength(-1);
        newAttributeType22.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType22.setEqualityId("caseIgnoreMatch");
        newAttributeType22.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType22.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("documentPublisher");
        newAttributeType22.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.56", newAttributeType22);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType23 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.46", bootstrapRegistries);
        newAttributeType23.setDescription("RFC1274: Janet mailbox");
        newAttributeType23.setCanUserModify(true);
        newAttributeType23.setSingleValue(false);
        newAttributeType23.setCollective(false);
        newAttributeType23.setObsolete(false);
        newAttributeType23.setLength(256);
        newAttributeType23.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType23.setEqualityId("caseIgnoreIA5Match");
        newAttributeType23.setSubstrId("caseIgnoreIA5SubstringsMatch");
        newAttributeType23.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("janetMailbox");
        newAttributeType23.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.46", newAttributeType23);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType24 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.13", bootstrapRegistries);
        newAttributeType24.setDescription("RFC1274: version of document");
        newAttributeType24.setCanUserModify(true);
        newAttributeType24.setSingleValue(false);
        newAttributeType24.setCollective(false);
        newAttributeType24.setObsolete(false);
        newAttributeType24.setLength(256);
        newAttributeType24.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType24.setEqualityId("caseIgnoreMatch");
        newAttributeType24.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType24.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("documentVersion");
        newAttributeType24.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.13", newAttributeType24);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType25 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.47", bootstrapRegistries);
        newAttributeType25.setDescription("RFC1274: mail preference option");
        newAttributeType25.setCanUserModify(true);
        newAttributeType25.setSingleValue(false);
        newAttributeType25.setCollective(false);
        newAttributeType25.setObsolete(false);
        newAttributeType25.setLength(-1);
        newAttributeType25.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType25.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("mailPreferenceOption");
        newAttributeType25.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.47", newAttributeType25);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType26 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.55", bootstrapRegistries);
        newAttributeType26.setDescription("RFC1274: audio (u-law)");
        newAttributeType26.setCanUserModify(true);
        newAttributeType26.setSingleValue(false);
        newAttributeType26.setCollective(false);
        newAttributeType26.setObsolete(false);
        newAttributeType26.setLength(25000);
        newAttributeType26.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType26.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.4");
        arrayList.clear();
        arrayList.add("audio");
        newAttributeType26.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.55", newAttributeType26);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType27 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.5", bootstrapRegistries);
        newAttributeType27.setDescription("RFC1274: favorite drink");
        newAttributeType27.setCanUserModify(true);
        newAttributeType27.setSingleValue(false);
        newAttributeType27.setCollective(false);
        newAttributeType27.setObsolete(false);
        newAttributeType27.setLength(256);
        newAttributeType27.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType27.setEqualityId("caseIgnoreMatch");
        newAttributeType27.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType27.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("drink");
        arrayList.add("favouriteDrink");
        newAttributeType27.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.5", newAttributeType27);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType28 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.14", bootstrapRegistries);
        newAttributeType28.setDescription("RFC1274: DN of author of document");
        newAttributeType28.setCanUserModify(true);
        newAttributeType28.setSingleValue(false);
        newAttributeType28.setCollective(false);
        newAttributeType28.setObsolete(false);
        newAttributeType28.setLength(-1);
        newAttributeType28.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType28.setEqualityId("distinguishedNameMatch");
        newAttributeType28.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("documentAuthor");
        newAttributeType28.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.14", newAttributeType28);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType29 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.4", bootstrapRegistries);
        newAttributeType29.setDescription("RFC1274: general information");
        newAttributeType29.setCanUserModify(true);
        newAttributeType29.setSingleValue(false);
        newAttributeType29.setCollective(false);
        newAttributeType29.setObsolete(false);
        newAttributeType29.setLength(2048);
        newAttributeType29.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType29.setEqualityId("caseIgnoreMatch");
        newAttributeType29.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType29.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("info");
        newAttributeType29.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.4", newAttributeType29);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType30 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.48", bootstrapRegistries);
        newAttributeType30.setDescription("RFC1274: name of building");
        newAttributeType30.setCanUserModify(true);
        newAttributeType30.setSingleValue(false);
        newAttributeType30.setCollective(false);
        newAttributeType30.setObsolete(false);
        newAttributeType30.setLength(256);
        newAttributeType30.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType30.setEqualityId("caseIgnoreMatch");
        newAttributeType30.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType30.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("buildingName");
        newAttributeType30.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.48", newAttributeType30);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType31 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.11", bootstrapRegistries);
        newAttributeType31.setDescription("RFC1274: unique identifier of document");
        newAttributeType31.setCanUserModify(true);
        newAttributeType31.setSingleValue(false);
        newAttributeType31.setCollective(false);
        newAttributeType31.setObsolete(false);
        newAttributeType31.setLength(256);
        newAttributeType31.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType31.setEqualityId("caseIgnoreMatch");
        newAttributeType31.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType31.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("documentIdentifier");
        newAttributeType31.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.11", newAttributeType31);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType32 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.26", bootstrapRegistries);
        newAttributeType32.setCanUserModify(true);
        newAttributeType32.setSingleValue(false);
        newAttributeType32.setCollective(false);
        newAttributeType32.setObsolete(false);
        newAttributeType32.setLength(-1);
        newAttributeType32.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType32.setEqualityId("caseIgnoreIA5Match");
        newAttributeType32.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("aRecord");
        newAttributeType32.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.26", newAttributeType32);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType33 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.42", bootstrapRegistries);
        newAttributeType33.setDescription("RFC1274: pager telephone number");
        newAttributeType33.setCanUserModify(true);
        newAttributeType33.setSingleValue(false);
        newAttributeType33.setCollective(false);
        newAttributeType33.setObsolete(false);
        newAttributeType33.setLength(-1);
        newAttributeType33.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType33.setEqualityId("telephoneNumberMatch");
        newAttributeType33.setSubstrId("telephoneNumberSubstringsMatch");
        newAttributeType33.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.50");
        arrayList.clear();
        arrayList.add("pager");
        arrayList.add("pagerTelephoneNumber");
        newAttributeType33.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.42", newAttributeType33);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType34 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.39", bootstrapRegistries);
        newAttributeType34.setDescription("RFC1274: home postal address");
        newAttributeType34.setCanUserModify(true);
        newAttributeType34.setSingleValue(false);
        newAttributeType34.setCollective(false);
        newAttributeType34.setObsolete(false);
        newAttributeType34.setLength(-1);
        newAttributeType34.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType34.setEqualityId("caseIgnoreListMatch");
        newAttributeType34.setSubstrId("caseIgnoreListSubstringsMatch");
        newAttributeType34.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.41");
        arrayList.clear();
        arrayList.add("homePostalAddress");
        newAttributeType34.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.39", newAttributeType34);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType35 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.28", bootstrapRegistries);
        newAttributeType35.setCanUserModify(true);
        newAttributeType35.setSingleValue(false);
        newAttributeType35.setCollective(false);
        newAttributeType35.setObsolete(false);
        newAttributeType35.setLength(-1);
        newAttributeType35.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType35.setEqualityId("caseIgnoreIA5Match");
        newAttributeType35.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("mXRecord");
        newAttributeType35.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.28", newAttributeType35);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType36 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.45", bootstrapRegistries);
        newAttributeType36.setDescription("RFC1274: organizational status");
        newAttributeType36.setCanUserModify(true);
        newAttributeType36.setSingleValue(false);
        newAttributeType36.setCollective(false);
        newAttributeType36.setObsolete(false);
        newAttributeType36.setLength(256);
        newAttributeType36.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType36.setEqualityId("caseIgnoreMatch");
        newAttributeType36.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType36.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("organizationalStatus");
        newAttributeType36.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.45", newAttributeType36);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType37 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.38", bootstrapRegistries);
        newAttributeType37.setDescription("RFC1274: DN of entry associated with domain");
        newAttributeType37.setCanUserModify(true);
        newAttributeType37.setSingleValue(false);
        newAttributeType37.setCollective(false);
        newAttributeType37.setObsolete(false);
        newAttributeType37.setLength(-1);
        newAttributeType37.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType37.setEqualityId("distinguishedNameMatch");
        newAttributeType37.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("associatedName");
        newAttributeType37.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.38", newAttributeType37);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType38 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.6", bootstrapRegistries);
        newAttributeType38.setDescription("RFC1274: room number");
        newAttributeType38.setCanUserModify(true);
        newAttributeType38.setSingleValue(false);
        newAttributeType38.setCollective(false);
        newAttributeType38.setObsolete(false);
        newAttributeType38.setLength(256);
        newAttributeType38.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType38.setEqualityId("caseIgnoreMatch");
        newAttributeType38.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType38.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("roomNumber");
        newAttributeType38.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.6", newAttributeType38);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType39 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.31", bootstrapRegistries);
        newAttributeType39.setCanUserModify(true);
        newAttributeType39.setSingleValue(false);
        newAttributeType39.setCollective(false);
        newAttributeType39.setObsolete(false);
        newAttributeType39.setLength(-1);
        newAttributeType39.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType39.setEqualityId("caseIgnoreIA5Match");
        newAttributeType39.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("cNAMERecord");
        newAttributeType39.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.31", newAttributeType39);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType40 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.53", bootstrapRegistries);
        newAttributeType40.setDescription("RFC1274: Personal Signature (G3 fax)");
        newAttributeType40.setCanUserModify(true);
        newAttributeType40.setSingleValue(false);
        newAttributeType40.setCollective(false);
        newAttributeType40.setObsolete(false);
        newAttributeType40.setLength(-1);
        newAttributeType40.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType40.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.23");
        arrayList.clear();
        arrayList.add("personalSignature");
        newAttributeType40.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.53", newAttributeType40);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType41 = AbstractBootstrapProducer.newAttributeType("0.9.2342.19200300.100.1.20", bootstrapRegistries);
        newAttributeType41.setDescription("RFC1274: home telephone number");
        newAttributeType41.setCanUserModify(true);
        newAttributeType41.setSingleValue(false);
        newAttributeType41.setCollective(false);
        newAttributeType41.setObsolete(false);
        newAttributeType41.setLength(-1);
        newAttributeType41.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType41.setEqualityId("telephoneNumberMatch");
        newAttributeType41.setSubstrId("telephoneNumberSubstringsMatch");
        newAttributeType41.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.50");
        arrayList.clear();
        arrayList.add("homePhone");
        arrayList.add("homeTelephoneNumber");
        newAttributeType41.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.1.20", newAttributeType41);
    }
}
