package org.apache.ldap.server.schema.bootstrap;

import java.util.ArrayList;
import javax.naming.NamingException;
import org.apache.ldap.server.jndi.JavaLdapSupport;
import org.apache.ldap.server.schema.bootstrap.AbstractBootstrapProducer;
/* loaded from: classes3.dex */
public class CosineObjectClassProducer extends AbstractBootstrapProducer {
    public CosineObjectClassProducer() {
        super(ProducerTypeEnum.OBJECT_CLASS_PRODUCER);
    }

    @Override // org.apache.ldap.server.schema.bootstrap.BootstrapProducer
    public void produce(BootstrapRegistries bootstrapRegistries, ProducerCallback producerCallback) throws NamingException {
        ArrayList arrayList = new ArrayList();
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.13", bootstrapRegistries);
        newObjectClass.setObsolete(false);
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("domainComponent");
        newObjectClass.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("associatedName");
        arrayList.add("organizationName");
        arrayList.add("description");
        arrayList.add("businessCategory");
        arrayList.add("seeAlso");
        arrayList.add("searchGuide");
        arrayList.add("userPassword");
        arrayList.add("localityName");
        arrayList.add("stateOrProvinceName");
        arrayList.add("streetAddress");
        arrayList.add("physicalDeliveryOfficeName");
        arrayList.add("postalAddress");
        arrayList.add("postalCode");
        arrayList.add("postOfficeBox");
        arrayList.add("streetAddress");
        arrayList.add("facsimileTelephoneNumber");
        arrayList.add("internationalISDNNumber");
        arrayList.add("telephoneNumber");
        arrayList.add("teletexTerminalIdentifier");
        arrayList.add("telexNumber");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("destinationIndicator");
        arrayList.add("registeredAddress");
        arrayList.add("x121Address");
        newObjectClass.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("domain");
        newObjectClass.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.13", newObjectClass);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass2 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.22", bootstrapRegistries);
        newObjectClass2.setObsolete(false);
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass2.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dsaQuality");
        newObjectClass2.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("subtreeMinimumQuality");
        arrayList.add("subtreeMaximumQuality");
        newObjectClass2.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("qualityLabelledData");
        newObjectClass2.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.22", newObjectClass2);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass3 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.4", bootstrapRegistries);
        newObjectClass3.setObsolete(false);
        arrayList.clear();
        arrayList.add("person");
        newObjectClass3.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass3.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userid");
        arrayList.add("textEncodedORAddress");
        arrayList.add("rfc822Mailbox");
        arrayList.add("favouriteDrink");
        arrayList.add("roomNumber");
        arrayList.add("userClass");
        arrayList.add("homeTelephoneNumber");
        arrayList.add("homePostalAddress");
        arrayList.add("secretary");
        arrayList.add("personalTitle");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("businessCategory");
        arrayList.add("janetMailbox");
        arrayList.add("otherMailbox");
        arrayList.add("mobileTelephoneNumber");
        arrayList.add("pagerTelephoneNumber");
        arrayList.add("organizationalStatus");
        arrayList.add("mailPreferenceOption");
        arrayList.add("personalSignature");
        newObjectClass3.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("pilotPerson");
        arrayList.add("newPilotPerson");
        newObjectClass3.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.4", newObjectClass3);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass4 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.17", bootstrapRegistries);
        newObjectClass4.setObsolete(false);
        newObjectClass4.setDescription("RFC1274: an object related to an domain");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass4.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("associatedDomain");
        newObjectClass4.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass4.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("domainRelatedObject");
        newObjectClass4.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.17", newObjectClass4);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass5 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.7", bootstrapRegistries);
        newObjectClass5.setObsolete(false);
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass5.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("commonName");
        newObjectClass5.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("roomNumber");
        arrayList.add("description");
        arrayList.add("seeAlso");
        arrayList.add("telephoneNumber");
        newObjectClass5.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("room");
        newObjectClass5.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.7", newObjectClass5);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass6 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.21", bootstrapRegistries);
        newObjectClass6.setObsolete(false);
        arrayList.clear();
        arrayList.add("dsa");
        newObjectClass6.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass6.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dSAQuality");
        newObjectClass6.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("pilotDSA");
        newObjectClass6.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.21", newObjectClass6);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass7 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.6", bootstrapRegistries);
        newObjectClass7.setObsolete(false);
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass7.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("documentIdentifier");
        newObjectClass7.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("commonName");
        arrayList.add("description");
        arrayList.add("seeAlso");
        arrayList.add("localityName");
        arrayList.add("organizationName");
        arrayList.add("organizationalUnitName");
        arrayList.add("documentTitle");
        arrayList.add("documentVersion");
        arrayList.add("documentAuthor");
        arrayList.add("documentLocation");
        arrayList.add("documentPublisher");
        newObjectClass7.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("document");
        newObjectClass7.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.6", newObjectClass7);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass8 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.15", bootstrapRegistries);
        newObjectClass8.setObsolete(false);
        arrayList.clear();
        arrayList.add("domain");
        newObjectClass8.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass8.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("ARecord");
        arrayList.add("MDRecord");
        arrayList.add("MXRecord");
        arrayList.add("NSRecord");
        arrayList.add("SOARecord");
        arrayList.add("CNAMERecord");
        newObjectClass8.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dNSDomain");
        newObjectClass8.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.15", newObjectClass8);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass9 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.9", bootstrapRegistries);
        newObjectClass9.setObsolete(false);
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass9.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("commonName");
        newObjectClass9.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("description");
        arrayList.add("seeAlso");
        arrayList.add("telephonenumber");
        arrayList.add("localityName");
        arrayList.add("organizationName");
        arrayList.add("organizationalUnitName");
        newObjectClass9.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("documentSeries");
        newObjectClass9.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.9", newObjectClass9);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass10 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.20", bootstrapRegistries);
        newObjectClass10.setObsolete(false);
        arrayList.clear();
        arrayList.add("organization");
        arrayList.add("organizationalUnit");
        newObjectClass10.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass10.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("buildingName");
        newObjectClass10.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("pilotOrganization");
        newObjectClass10.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.20", newObjectClass10);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass11 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.5", bootstrapRegistries);
        newObjectClass11.setObsolete(false);
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass11.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userid");
        newObjectClass11.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("description");
        arrayList.add("seeAlso");
        arrayList.add("localityName");
        arrayList.add("organizationName");
        arrayList.add("organizationalUnitName");
        arrayList.add("host");
        newObjectClass11.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("account");
        newObjectClass11.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.5", newObjectClass11);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass12 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.14", bootstrapRegistries);
        newObjectClass12.setObsolete(false);
        arrayList.clear();
        arrayList.add("domain");
        newObjectClass12.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass12.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("commonName");
        arrayList.add("surname");
        arrayList.add("description");
        arrayList.add("seeAlso");
        arrayList.add("telephoneNumber");
        arrayList.add("physicalDeliveryOfficeName");
        arrayList.add("postalAddress");
        arrayList.add("postalCode");
        arrayList.add("postOfficeBox");
        arrayList.add("streetAddress");
        arrayList.add("facsimileTelephoneNumber");
        arrayList.add("internationalISDNNumber");
        arrayList.add("telephoneNumber");
        arrayList.add("teletexTerminalIdentifier");
        arrayList.add("telexNumber");
        arrayList.add("preferredDeliveryMethod");
        arrayList.add("destinationIndicator");
        arrayList.add("registeredAddress");
        arrayList.add("x121Address");
        newObjectClass12.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("RFC822localPart");
        newObjectClass12.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.14", newObjectClass12);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass13 = AbstractBootstrapProducer.newObjectClass("0.9.2342.19200300.100.4.18", bootstrapRegistries);
        newObjectClass13.setObsolete(false);
        arrayList.clear();
        arrayList.add("country");
        newObjectClass13.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("friendlyCountryName");
        newObjectClass13.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass13.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("friendlyCountry");
        newObjectClass13.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "0.9.2342.19200300.100.4.18", newObjectClass13);
    }
}
