package org.apache.ldap.server.schema.bootstrap;

import java.util.ArrayList;
import javax.naming.NamingException;
import org.apache.ldap.server.jndi.JavaLdapSupport;
import org.apache.ldap.server.schema.bootstrap.AbstractBootstrapProducer;
/* loaded from: classes3.dex */
public class DhcpObjectClassProducer extends AbstractBootstrapProducer {
    public DhcpObjectClassProducer() {
        super(ProducerTypeEnum.OBJECT_CLASS_PRODUCER);
    }

    @Override // org.apache.ldap.server.schema.bootstrap.BootstrapProducer
    public void produce(BootstrapRegistries bootstrapRegistries, ProducerCallback producerCallback) throws NamingException {
        ArrayList arrayList = new ArrayList();
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.5", bootstrapRegistries);
        newObjectClass.setObsolete(false);
        newObjectClass.setDescription("Group object that lists host DNs and parameters. This is a container object.");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpHostDN");
        arrayList.add("dhcpOptionsDN");
        arrayList.add("dhcpStatements");
        newObjectClass.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpGroup");
        newObjectClass.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.5", newObjectClass);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass2 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.3", bootstrapRegistries);
        newObjectClass2.setObsolete(false);
        newObjectClass2.setDescription("This class defines a subnet. This is a container object.");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass2.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("dhcpNetMask");
        newObjectClass2.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpRange");
        arrayList.add("dhcpPoolDN");
        arrayList.add("dhcpGroupDN");
        arrayList.add("dhcpHostDN");
        arrayList.add("dhcpClassesDN");
        arrayList.add("dhcpLeasesDN");
        arrayList.add("dhcpOptionsDN");
        arrayList.add("dhcpStatements");
        newObjectClass2.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpSubnet");
        newObjectClass2.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.3", newObjectClass2);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass3 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.8", bootstrapRegistries);
        newObjectClass3.setObsolete(false);
        newObjectClass3.setDescription("Represents information about a collection of related classes.");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass3.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass3.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpClassData");
        arrayList.add("dhcpOptionsDN");
        arrayList.add("dhcpStatements");
        newObjectClass3.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpSubClass");
        newObjectClass3.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.8", newObjectClass3);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass4 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.2", bootstrapRegistries);
        newObjectClass4.setObsolete(false);
        newObjectClass4.setDescription("This stores configuration information for a shared network.");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass4.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass4.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpSubnetDN");
        arrayList.add("dhcpPoolDN");
        arrayList.add("dhcpOptionsDN");
        arrayList.add("dhcpStatements");
        newObjectClass4.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpSharedNetwork");
        newObjectClass4.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.2", newObjectClass4);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass5 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.11", bootstrapRegistries);
        newObjectClass5.setObsolete(false);
        newObjectClass5.setDescription("This is the object that holds past information about the IP address. The cn is the time/date stamp when the address was assigned or released, the address state at the time, if the address was assigned or released.");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass5.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass5.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpAddressState");
        arrayList.add("dhcpExpirationTime");
        arrayList.add("dhcpStartTimeOfState");
        arrayList.add("dhcpLastTransactionTime");
        arrayList.add("dhcpBootpFlag");
        arrayList.add("dhcpDomainName");
        arrayList.add("dhcpDnsStatus");
        arrayList.add("dhcpRequestedHostName");
        arrayList.add("dhcpAssignedHostName");
        arrayList.add("dhcpReservedForClient");
        arrayList.add("dhcpAssignedToClient");
        arrayList.add("dhcpRelayAgentInfo");
        arrayList.add("dhcpHWAddress");
        arrayList.add("dhcpErrorLog");
        newObjectClass5.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpLog");
        newObjectClass5.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.11", newObjectClass5);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass6 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.4", bootstrapRegistries);
        newObjectClass6.setObsolete(false);
        newObjectClass6.setDescription("This stores configuration information about a pool.");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass6.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("dhcpRange");
        newObjectClass6.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpClassesDN");
        arrayList.add("dhcpPermitList");
        arrayList.add("dhcpLeasesDN");
        arrayList.add("dhcpOptionsDN");
        arrayList.add("dhcpStatements");
        newObjectClass6.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpPool");
        newObjectClass6.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.4", newObjectClass6);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass7 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.12", bootstrapRegistries);
        newObjectClass7.setObsolete(false);
        newObjectClass7.setDescription("DHCP Server Object");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass7.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("dhcpServiceDN");
        newObjectClass7.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpVersion");
        arrayList.add("dhcpImplementation");
        arrayList.add("dhcpHashBucketAssignment");
        arrayList.add("dhcpDelayedServiceParameter");
        arrayList.add("dhcpMaxClientLeadTime");
        arrayList.add("dhcpFailOverEndpointState");
        arrayList.add("dhcpStatements");
        newObjectClass7.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpServer");
        newObjectClass7.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.12", newObjectClass7);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass8 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.9", bootstrapRegistries);
        newObjectClass8.setObsolete(false);
        newObjectClass8.setDescription("Represents information about a collection of options defined.");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass8.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass8.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpOption");
        newObjectClass8.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpOptions");
        newObjectClass8.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.9", newObjectClass8);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass9 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.6", bootstrapRegistries);
        newObjectClass9.setObsolete(false);
        newObjectClass9.setDescription("This represents information about a particular client");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass9.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass9.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpLeaseDN");
        arrayList.add("dhcpHWAddress");
        arrayList.add("dhcpOptionsDN");
        arrayList.add("dhcpStatements");
        newObjectClass9.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpHost");
        newObjectClass9.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.6", newObjectClass9);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass10 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.1", bootstrapRegistries);
        newObjectClass10.setObsolete(false);
        newObjectClass10.setDescription("Service object that represents the actual DHCP Service configuration. This is a container object.");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass10.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("dhcpPrimaryDN");
        newObjectClass10.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpSecondaryDN");
        arrayList.add("dhcpSharedNetworkDN");
        arrayList.add("dhcpSubnetDN");
        arrayList.add("dhcpGroupDN");
        arrayList.add("dhcpHostDN");
        arrayList.add("dhcpClassesDN");
        arrayList.add("dhcpOptionsDN");
        arrayList.add("dhcpStatements");
        newObjectClass10.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpService");
        newObjectClass10.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.1", newObjectClass10);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass11 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.10", bootstrapRegistries);
        newObjectClass11.setObsolete(false);
        newObjectClass11.setDescription("This class represents an IP Address, which may or may not have been leased.");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass11.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("dhcpAddressState");
        newObjectClass11.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpExpirationTime");
        arrayList.add("dhcpStartTimeOfState");
        arrayList.add("dhcpLastTransactionTime");
        arrayList.add("dhcpBootpFlag");
        arrayList.add("dhcpDomainName");
        arrayList.add("dhcpDnsStatus");
        arrayList.add("dhcpRequestedHostName");
        arrayList.add("dhcpAssignedHostName");
        arrayList.add("dhcpReservedForClient");
        arrayList.add("dhcpAssignedToClient");
        arrayList.add("dhcpRelayAgentInfo");
        arrayList.add("dhcpHWAddress");
        newObjectClass11.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpLeases");
        newObjectClass11.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.10", newObjectClass11);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass12 = AbstractBootstrapProducer.newObjectClass("2.16.840.1.113719.1.203.6.7", bootstrapRegistries);
        newObjectClass12.setObsolete(false);
        newObjectClass12.setDescription("Represents information about a collection of related clients.");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass12.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass12.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpSubClassesDN");
        arrayList.add("dhcpOptionsDN");
        arrayList.add("dhcpStatements");
        newObjectClass12.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("dhcpClass");
        newObjectClass12.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113719.1.203.6.7", newObjectClass12);
    }
}
