package org.apache.ldap.server.schema.bootstrap;

import java.util.ArrayList;
import javax.naming.NamingException;
import org.apache.ldap.server.jndi.JavaLdapSupport;
import org.apache.ldap.server.schema.bootstrap.AbstractBootstrapProducer;
/* loaded from: classes3.dex */
public class NisObjectClassProducer extends AbstractBootstrapProducer {
    public NisObjectClassProducer() {
        super(ProducerTypeEnum.OBJECT_CLASS_PRODUCER);
    }

    @Override // org.apache.ldap.server.schema.bootstrap.BootstrapProducer
    public void produce(BootstrapRegistries bootstrapRegistries, ProducerCallback producerCallback) throws NamingException {
        ArrayList arrayList = new ArrayList();
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.4", bootstrapRegistries);
        newObjectClass.setObsolete(false);
        newObjectClass.setDescription("Abstraction of an IP protocol");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("ipProtocolNumber");
        arrayList.add("description");
        newObjectClass.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("description");
        newObjectClass.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("ipProtocol");
        newObjectClass.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.4", newObjectClass);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass2 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.3", bootstrapRegistries);
        newObjectClass2.setObsolete(false);
        newObjectClass2.setDescription("Abstraction an Internet Protocol service");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass2.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("ipServicePort");
        arrayList.add("ipServiceProtocol");
        newObjectClass2.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("description");
        newObjectClass2.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("ipService");
        newObjectClass2.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.3", newObjectClass2);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass3 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.12", bootstrapRegistries);
        newObjectClass3.setObsolete(false);
        newObjectClass3.setDescription("A device with boot parameters");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass3.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass3.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("bootFile");
        arrayList.add("bootParameter");
        newObjectClass3.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("bootableDevice");
        newObjectClass3.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.12", newObjectClass3);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass4 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.2", bootstrapRegistries);
        newObjectClass4.setObsolete(false);
        newObjectClass4.setDescription("Abstraction of a group of accounts");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass4.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("gidNumber");
        newObjectClass4.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userPassword");
        arrayList.add("memberUid");
        arrayList.add("description");
        newObjectClass4.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("posixGroup");
        newObjectClass4.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.2", newObjectClass4);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass5 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.5", bootstrapRegistries);
        newObjectClass5.setObsolete(false);
        newObjectClass5.setDescription("Abstraction of an ONC/RPC binding");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass5.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("oncRpcNumber");
        arrayList.add("description");
        newObjectClass5.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("description");
        newObjectClass5.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("oncRpc");
        newObjectClass5.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.5", newObjectClass5);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass6 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.8", bootstrapRegistries);
        newObjectClass6.setObsolete(false);
        newObjectClass6.setDescription("Abstraction of a netgroup");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass6.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        newObjectClass6.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("nisNetgroupTriple");
        arrayList.add("memberNisNetgroup");
        arrayList.add("description");
        newObjectClass6.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("nisNetgroup");
        newObjectClass6.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.8", newObjectClass6);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass7 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.6", bootstrapRegistries);
        newObjectClass7.setObsolete(false);
        newObjectClass7.setDescription("Abstraction of a host, an IP device");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass7.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("ipHostNumber");
        newObjectClass7.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("l");
        arrayList.add("description");
        arrayList.add("manager");
        newObjectClass7.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("ipHost");
        newObjectClass7.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.6", newObjectClass7);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass8 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.9", bootstrapRegistries);
        newObjectClass8.setObsolete(false);
        newObjectClass8.setDescription("A generic abstraction of a NIS map");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass8.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("nisMapName");
        newObjectClass8.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("description");
        newObjectClass8.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("nisMap");
        newObjectClass8.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.9", newObjectClass8);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass9 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.1", bootstrapRegistries);
        newObjectClass9.setObsolete(false);
        newObjectClass9.setDescription("Additional attributes for shadow passwords");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass9.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("uid");
        newObjectClass9.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userPassword");
        arrayList.add("shadowLastChange");
        arrayList.add("shadowMin");
        arrayList.add("shadowMax");
        arrayList.add("shadowWarning");
        arrayList.add("shadowInactive");
        arrayList.add("shadowExpire");
        arrayList.add("shadowFlag");
        arrayList.add("description");
        newObjectClass9.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("shadowAccount");
        newObjectClass9.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.1", newObjectClass9);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass10 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.10", bootstrapRegistries);
        newObjectClass10.setObsolete(false);
        newObjectClass10.setDescription("An entry in a NIS map");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass10.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("nisMapEntry");
        arrayList.add("nisMapName");
        newObjectClass10.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("description");
        newObjectClass10.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("nisObject");
        newObjectClass10.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.10", newObjectClass10);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass11 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.0", bootstrapRegistries);
        newObjectClass11.setObsolete(false);
        newObjectClass11.setDescription("Abstraction of an account with POSIX attributes");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass11.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("uid");
        arrayList.add("uidNumber");
        arrayList.add("gidNumber");
        arrayList.add("homeDirectory");
        newObjectClass11.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("userPassword");
        arrayList.add("loginShell");
        arrayList.add("gecos");
        arrayList.add("description");
        newObjectClass11.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("posixAccount");
        newObjectClass11.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.0", newObjectClass11);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass12 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.7", bootstrapRegistries);
        newObjectClass12.setObsolete(false);
        newObjectClass12.setDescription("Abstraction of an IP network");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass12.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("ipNetworkNumber");
        newObjectClass12.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("ipNetmaskNumber");
        arrayList.add("l");
        arrayList.add("description");
        arrayList.add("manager");
        newObjectClass12.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("ipNetwork");
        newObjectClass12.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.7", newObjectClass12);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass13 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.1.1.2.11", bootstrapRegistries);
        newObjectClass13.setObsolete(false);
        newObjectClass13.setDescription("A device with a MAC address");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass13.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass13.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("macAddress");
        newObjectClass13.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("ieee802Device");
        newObjectClass13.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.1.2.11", newObjectClass13);
    }
}
