package org.apache.ldap.server.schema.bootstrap;

import java.util.ArrayList;
import javax.naming.NamingException;
import org.apache.ldap.server.jndi.JavaLdapSupport;
import org.apache.ldap.server.schema.bootstrap.AbstractBootstrapProducer;
/* loaded from: classes3.dex */
public class SambaObjectClassProducer extends AbstractBootstrapProducer {
    public SambaObjectClassProducer() {
        super(ProducerTypeEnum.OBJECT_CLASS_PRODUCER);
    }

    @Override // org.apache.ldap.server.schema.bootstrap.BootstrapProducer
    public void produce(BootstrapRegistries bootstrapRegistries, ProducerCallback producerCallback) throws NamingException {
        ArrayList arrayList = new ArrayList();
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.2.2.9", bootstrapRegistries);
        newObjectClass.setObsolete(false);
        newObjectClass.setDescription("Structural Class for a SID");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaSID");
        newObjectClass.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaSidEntry");
        newObjectClass.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.2.9", newObjectClass);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass2 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.2.2.6", bootstrapRegistries);
        newObjectClass2.setObsolete(false);
        newObjectClass2.setDescription("Samba 3.0 Auxilary SAM Account");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass2.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("uid");
        arrayList.add("sambaSID");
        newObjectClass2.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("sambaLMPassword");
        arrayList.add("sambaNTPassword");
        arrayList.add("sambaPwdLastSet");
        arrayList.add("sambaLogonTime");
        arrayList.add("sambaLogoffTime");
        arrayList.add("sambaKickoffTime");
        arrayList.add("sambaPwdCanChange");
        arrayList.add("sambaPwdMustChange");
        arrayList.add("sambaAcctFlags");
        arrayList.add("displayName");
        arrayList.add("sambaHomePath");
        arrayList.add("sambaHomeDrive");
        arrayList.add("sambaLogonScript");
        arrayList.add("sambaProfilePath");
        arrayList.add("description");
        arrayList.add("sambaUserWorkstations");
        arrayList.add("sambaPrimaryGroupSID");
        arrayList.add("sambaDomainName");
        arrayList.add("sambaMungedDial");
        arrayList.add("sambaBadPasswordCount");
        arrayList.add("sambaBadPasswordTime");
        arrayList.add("sambaPasswordHistory");
        arrayList.add("sambaLogonHours");
        newObjectClass2.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaSamAccount");
        newObjectClass2.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.2.6", newObjectClass2);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass3 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.2.2.5", bootstrapRegistries);
        newObjectClass3.setObsolete(false);
        newObjectClass3.setDescription("Samba Domain Information");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass3.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaDomainName");
        arrayList.add("sambaSID");
        newObjectClass3.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaNextRid");
        arrayList.add("sambaNextGroupRid");
        arrayList.add("sambaNextUserRid");
        arrayList.add("sambaAlgorithmicRidBase");
        newObjectClass3.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaDomain");
        newObjectClass3.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.2.5", newObjectClass3);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass4 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.2.2.13", bootstrapRegistries);
        newObjectClass4.setObsolete(false);
        newObjectClass4.setDescription("Samba Privilege");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass4.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaSID");
        newObjectClass4.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaPrivilegeList");
        newObjectClass4.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaPrivilege");
        newObjectClass4.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.2.13", newObjectClass4);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass5 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.2.2.4", bootstrapRegistries);
        newObjectClass5.setObsolete(false);
        newObjectClass5.setDescription("Samba Group Mapping");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass5.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("gidNumber");
        arrayList.add("sambaSID");
        arrayList.add("sambaGroupType");
        newObjectClass5.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("displayName");
        arrayList.add("description");
        arrayList.add("sambaSIDList");
        newObjectClass5.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaGroupMapping");
        newObjectClass5.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.2.4", newObjectClass5);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass6 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.2.2.11", bootstrapRegistries);
        newObjectClass6.setObsolete(false);
        newObjectClass6.setDescription("Samba Share Section");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass6.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaShareName");
        newObjectClass6.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("description");
        newObjectClass6.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaShare");
        newObjectClass6.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.2.11", newObjectClass6);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass7 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.2.2.8", bootstrapRegistries);
        newObjectClass7.setObsolete(false);
        newObjectClass7.setDescription("Mapping from a SID to an ID");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass7.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaSID");
        newObjectClass7.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("uidNumber");
        arrayList.add("gidNumber");
        newObjectClass7.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaIdmapEntry");
        newObjectClass7.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.2.8", newObjectClass7);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass8 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.2.2.7", bootstrapRegistries);
        newObjectClass8.setObsolete(false);
        newObjectClass8.setDescription("Pool for allocating UNIX uids/gids");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass8.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("uidNumber");
        arrayList.add("gidNumber");
        newObjectClass8.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass8.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaUnixIdPool");
        newObjectClass8.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.2.7", newObjectClass8);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass9 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.1.2.2.10", bootstrapRegistries);
        newObjectClass9.setObsolete(false);
        newObjectClass9.setDescription("Samba Configuration Section");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass9.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        newObjectClass9.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("description");
        newObjectClass9.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaConfig");
        newObjectClass9.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.1.2.2.10", newObjectClass9);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass10 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.2.2.14", bootstrapRegistries);
        newObjectClass10.setObsolete(false);
        newObjectClass10.setDescription("Samba Trust Password");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass10.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaDomainName");
        arrayList.add("sambaNTPassword");
        arrayList.add("sambaTrustFlags");
        newObjectClass10.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaSID");
        arrayList.add("sambaPwdLastSet");
        newObjectClass10.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaTrustPassword");
        newObjectClass10.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.2.14", newObjectClass10);
        AbstractBootstrapProducer.BootstrapObjectClass newObjectClass11 = AbstractBootstrapProducer.newObjectClass("1.3.6.1.4.1.7165.2.2.12", bootstrapRegistries);
        newObjectClass11.setObsolete(false);
        newObjectClass11.setDescription("Samba Configuration Option");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.TOP_ATTR);
        newObjectClass11.setSuperClassIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaOptionName");
        newObjectClass11.setMustListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaBoolOption");
        arrayList.add("sambaIntegerOption");
        arrayList.add("sambaStringOption");
        arrayList.add("sambaStringListoption");
        arrayList.add("description");
        newObjectClass11.setMayListIds((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        arrayList.clear();
        arrayList.add("sambaConfigOption");
        newObjectClass11.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.2.12", newObjectClass11);
    }
}
