package org.apache.ldap.server.schema.bootstrap;

import com.ironsource.mediationsdk.logger.IronSourceError;
import java.util.ArrayList;
import javax.naming.NamingException;
import org.apache.ldap.common.schema.UsageEnum;
import org.apache.ldap.server.schema.bootstrap.AbstractBootstrapProducer;
/* loaded from: classes3.dex */
public class SambaAttributeTypeProducer extends AbstractBootstrapProducer {
    public SambaAttributeTypeProducer() {
        super(ProducerTypeEnum.ATTRIBUTE_TYPE_PRODUCER);
    }

    @Override // org.apache.ldap.server.schema.bootstrap.BootstrapProducer
    public void produce(BootstrapRegistries bootstrapRegistries, ProducerCallback producerCallback) throws NamingException {
        ArrayList arrayList = new ArrayList();
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.49", bootstrapRegistries);
        newAttributeType.setDescription("Time of the last bad password attempt");
        newAttributeType.setCanUserModify(true);
        newAttributeType.setSingleValue(true);
        newAttributeType.setCollective(false);
        newAttributeType.setObsolete(false);
        newAttributeType.setLength(-1);
        newAttributeType.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType.setEqualityId("integerMatch");
        newAttributeType.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaBadPasswordTime");
        newAttributeType.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.49", newAttributeType);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType2 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.27", bootstrapRegistries);
        newAttributeType2.setDescription("Timestamp of the last password update");
        newAttributeType2.setCanUserModify(true);
        newAttributeType2.setSingleValue(true);
        newAttributeType2.setCollective(false);
        newAttributeType2.setObsolete(false);
        newAttributeType2.setLength(-1);
        newAttributeType2.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType2.setEqualityId("integerMatch");
        newAttributeType2.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaPwdLastSet");
        newAttributeType2.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.27", newAttributeType2);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType3 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.19", bootstrapRegistries);
        newAttributeType3.setDescription("NT Group Type");
        newAttributeType3.setCanUserModify(true);
        newAttributeType3.setSingleValue(true);
        newAttributeType3.setCollective(false);
        newAttributeType3.setObsolete(false);
        newAttributeType3.setLength(-1);
        newAttributeType3.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType3.setEqualityId("integerMatch");
        newAttributeType3.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaGroupType");
        newAttributeType3.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.19", newAttributeType3);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType4 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.43", bootstrapRegistries);
        newAttributeType4.setDescription("A boolean option");
        newAttributeType4.setCanUserModify(true);
        newAttributeType4.setSingleValue(true);
        newAttributeType4.setCollective(false);
        newAttributeType4.setObsolete(false);
        newAttributeType4.setLength(-1);
        newAttributeType4.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType4.setEqualityId("booleanMatch");
        newAttributeType4.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.7");
        arrayList.clear();
        arrayList.add("sambaBoolOption");
        newAttributeType4.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.43", newAttributeType4);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType5 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.21", bootstrapRegistries);
        newAttributeType5.setDescription("Next NT rid to give our for users");
        newAttributeType5.setCanUserModify(true);
        newAttributeType5.setSingleValue(true);
        newAttributeType5.setCollective(false);
        newAttributeType5.setObsolete(false);
        newAttributeType5.setLength(-1);
        newAttributeType5.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType5.setEqualityId("integerMatch");
        newAttributeType5.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaNextUserRid");
        newAttributeType5.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.21", newAttributeType5);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType6 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.50", bootstrapRegistries);
        newAttributeType6.setCanUserModify(true);
        newAttributeType6.setSingleValue(false);
        newAttributeType6.setCollective(false);
        newAttributeType6.setObsolete(false);
        newAttributeType6.setLength(-1);
        newAttributeType6.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType6.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("sambaPrivName");
        newAttributeType6.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.50", newAttributeType6);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType7 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.40", bootstrapRegistries);
        newAttributeType7.setDescription("Base at which the samba RID generation algorithm should operate");
        newAttributeType7.setCanUserModify(true);
        newAttributeType7.setSingleValue(true);
        newAttributeType7.setCollective(false);
        newAttributeType7.setObsolete(false);
        newAttributeType7.setLength(-1);
        newAttributeType7.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType7.setEqualityId("integerMatch");
        newAttributeType7.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaAlgorithmicRidBase");
        newAttributeType7.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.40", newAttributeType7);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType8 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.29", bootstrapRegistries);
        newAttributeType8.setDescription("Timestamp of when the password will expire");
        newAttributeType8.setCanUserModify(true);
        newAttributeType8.setSingleValue(true);
        newAttributeType8.setCollective(false);
        newAttributeType8.setObsolete(false);
        newAttributeType8.setLength(-1);
        newAttributeType8.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType8.setEqualityId("integerMatch");
        newAttributeType8.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaPwdMustChange");
        newAttributeType8.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.29", newAttributeType8);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType9 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.39", bootstrapRegistries);
        newAttributeType9.setDescription("Next NT rid to give out for anything");
        newAttributeType9.setCanUserModify(true);
        newAttributeType9.setSingleValue(true);
        newAttributeType9.setCollective(false);
        newAttributeType9.setObsolete(false);
        newAttributeType9.setLength(-1);
        newAttributeType9.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType9.setEqualityId("integerMatch");
        newAttributeType9.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaNextRid");
        newAttributeType9.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.39", newAttributeType9);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType10 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.28", bootstrapRegistries);
        newAttributeType10.setDescription("Timestamp of when the user is allowed to update the password");
        newAttributeType10.setCanUserModify(true);
        newAttributeType10.setSingleValue(true);
        newAttributeType10.setCollective(false);
        newAttributeType10.setObsolete(false);
        newAttributeType10.setLength(-1);
        newAttributeType10.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType10.setEqualityId("integerMatch");
        newAttributeType10.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaPwdCanChange");
        newAttributeType10.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.28", newAttributeType10);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType11 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.55", bootstrapRegistries);
        newAttributeType11.setDescription("Logon Hours");
        newAttributeType11.setCanUserModify(true);
        newAttributeType11.setSingleValue(true);
        newAttributeType11.setCollective(false);
        newAttributeType11.setObsolete(false);
        newAttributeType11.setLength(42);
        newAttributeType11.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType11.setEqualityId("caseIgnoreIA5Match");
        newAttributeType11.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaLogonHours");
        newAttributeType11.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.55", newAttributeType11);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType12 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.20", bootstrapRegistries);
        newAttributeType12.setDescription("Security ID");
        newAttributeType12.setCanUserModify(true);
        newAttributeType12.setSingleValue(true);
        newAttributeType12.setCollective(false);
        newAttributeType12.setObsolete(false);
        newAttributeType12.setLength(64);
        newAttributeType12.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType12.setEqualityId("caseIgnoreIA5Match");
        newAttributeType12.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaSID");
        newAttributeType12.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.20", newAttributeType12);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType13 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.52", bootstrapRegistries);
        newAttributeType13.setDescription("Privileges List");
        newAttributeType13.setCanUserModify(true);
        newAttributeType13.setSingleValue(false);
        newAttributeType13.setCollective(false);
        newAttributeType13.setObsolete(false);
        newAttributeType13.setLength(64);
        newAttributeType13.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType13.setEqualityId("caseIgnoreIA5Match");
        newAttributeType13.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaPrivilegeList");
        newAttributeType13.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.52", newAttributeType13);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType14 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.42", bootstrapRegistries);
        newAttributeType14.setDescription("Option Name");
        newAttributeType14.setCanUserModify(true);
        newAttributeType14.setSingleValue(false);
        newAttributeType14.setCollective(false);
        newAttributeType14.setObsolete(false);
        newAttributeType14.setLength(256);
        newAttributeType14.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType14.setEqualityId("caseIgnoreMatch");
        newAttributeType14.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType14.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("sambaOptionName");
        newAttributeType14.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.42", newAttributeType14);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType15 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.48", bootstrapRegistries);
        newAttributeType15.setDescription("Bad password attempt count");
        newAttributeType15.setCanUserModify(true);
        newAttributeType15.setSingleValue(true);
        newAttributeType15.setCollective(false);
        newAttributeType15.setObsolete(false);
        newAttributeType15.setLength(-1);
        newAttributeType15.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType15.setEqualityId("integerMatch");
        newAttributeType15.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaBadPasswordCount");
        newAttributeType15.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.48", newAttributeType15);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType16 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.30", bootstrapRegistries);
        newAttributeType16.setDescription("Timestamp of last logon");
        newAttributeType16.setCanUserModify(true);
        newAttributeType16.setSingleValue(true);
        newAttributeType16.setCollective(false);
        newAttributeType16.setObsolete(false);
        newAttributeType16.setLength(-1);
        newAttributeType16.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType16.setEqualityId("integerMatch");
        newAttributeType16.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaLogonTime");
        newAttributeType16.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.30", newAttributeType16);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType17 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.41", bootstrapRegistries);
        newAttributeType17.setDescription("Share Name");
        newAttributeType17.setCanUserModify(true);
        newAttributeType17.setSingleValue(true);
        newAttributeType17.setCollective(false);
        newAttributeType17.setObsolete(false);
        newAttributeType17.setLength(-1);
        newAttributeType17.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType17.setEqualityId("caseIgnoreMatch");
        newAttributeType17.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("sambaShareName");
        newAttributeType17.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.41", newAttributeType17);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType18 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.26", bootstrapRegistries);
        newAttributeType18.setDescription("Account Flags");
        newAttributeType18.setCanUserModify(true);
        newAttributeType18.setSingleValue(true);
        newAttributeType18.setCollective(false);
        newAttributeType18.setObsolete(false);
        newAttributeType18.setLength(16);
        newAttributeType18.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType18.setEqualityId("caseIgnoreIA5Match");
        newAttributeType18.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaAcctFlags");
        newAttributeType18.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.26", newAttributeType18);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType19 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.38", bootstrapRegistries);
        newAttributeType19.setDescription("Windows NT domain to which the user belongs");
        newAttributeType19.setCanUserModify(true);
        newAttributeType19.setSingleValue(false);
        newAttributeType19.setCollective(false);
        newAttributeType19.setObsolete(false);
        newAttributeType19.setLength(128);
        newAttributeType19.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType19.setEqualityId("caseIgnoreMatch");
        newAttributeType19.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("sambaDomainName");
        newAttributeType19.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.38", newAttributeType19);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType20 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.32", bootstrapRegistries);
        newAttributeType20.setDescription("Timestamp of when the user will be logged off automatically");
        newAttributeType20.setCanUserModify(true);
        newAttributeType20.setSingleValue(true);
        newAttributeType20.setCollective(false);
        newAttributeType20.setObsolete(false);
        newAttributeType20.setLength(-1);
        newAttributeType20.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType20.setEqualityId("integerMatch");
        newAttributeType20.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaKickoffTime");
        newAttributeType20.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.32", newAttributeType20);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType21 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.54", bootstrapRegistries);
        newAttributeType21.setDescription("Concatenated MD4 hashes of the unicode passwords used on this account");
        newAttributeType21.setCanUserModify(true);
        newAttributeType21.setSingleValue(false);
        newAttributeType21.setCollective(false);
        newAttributeType21.setObsolete(false);
        newAttributeType21.setLength(32);
        newAttributeType21.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType21.setEqualityId("caseIgnoreIA5Match");
        newAttributeType21.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaPasswordHistory");
        newAttributeType21.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.54", newAttributeType21);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType22 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.44", bootstrapRegistries);
        newAttributeType22.setDescription("An integer option");
        newAttributeType22.setCanUserModify(true);
        newAttributeType22.setSingleValue(true);
        newAttributeType22.setCollective(false);
        newAttributeType22.setObsolete(false);
        newAttributeType22.setLength(-1);
        newAttributeType22.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType22.setEqualityId("integerMatch");
        newAttributeType22.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaIntegerOption");
        newAttributeType22.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.44", newAttributeType22);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType23 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.35", bootstrapRegistries);
        newAttributeType23.setDescription("Roaming profile path");
        newAttributeType23.setCanUserModify(true);
        newAttributeType23.setSingleValue(true);
        newAttributeType23.setCollective(false);
        newAttributeType23.setObsolete(false);
        newAttributeType23.setLength(255);
        newAttributeType23.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType23.setEqualityId("caseIgnoreMatch");
        newAttributeType23.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("sambaProfilePath");
        newAttributeType23.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.35", newAttributeType23);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType24 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.53", bootstrapRegistries);
        newAttributeType24.setDescription("Trust Password Flags");
        newAttributeType24.setCanUserModify(true);
        newAttributeType24.setSingleValue(false);
        newAttributeType24.setCollective(false);
        newAttributeType24.setObsolete(false);
        newAttributeType24.setLength(-1);
        newAttributeType24.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType24.setEqualityId("caseIgnoreIA5Match");
        newAttributeType24.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaTrustFlags");
        newAttributeType24.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.53", newAttributeType24);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType25 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.24", bootstrapRegistries);
        newAttributeType25.setDescription("LanManager Password");
        newAttributeType25.setCanUserModify(true);
        newAttributeType25.setSingleValue(true);
        newAttributeType25.setCollective(false);
        newAttributeType25.setObsolete(false);
        newAttributeType25.setLength(32);
        newAttributeType25.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType25.setEqualityId("caseIgnoreIA5Match");
        newAttributeType25.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaLMPassword");
        newAttributeType25.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.24", newAttributeType25);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType26 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.46", bootstrapRegistries);
        newAttributeType26.setDescription("A string list option");
        newAttributeType26.setCanUserModify(true);
        newAttributeType26.setSingleValue(false);
        newAttributeType26.setCollective(false);
        newAttributeType26.setObsolete(false);
        newAttributeType26.setLength(-1);
        newAttributeType26.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType26.setEqualityId("caseIgnoreMatch");
        newAttributeType26.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("sambaStringListOption");
        newAttributeType26.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.46", newAttributeType26);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType27 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.22", bootstrapRegistries);
        newAttributeType27.setDescription("Next NT rid to give out for groups");
        newAttributeType27.setCanUserModify(true);
        newAttributeType27.setSingleValue(true);
        newAttributeType27.setCollective(false);
        newAttributeType27.setObsolete(false);
        newAttributeType27.setLength(-1);
        newAttributeType27.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType27.setEqualityId("integerMatch");
        newAttributeType27.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaNextGroupRid");
        newAttributeType27.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.22", newAttributeType27);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType28 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.33", bootstrapRegistries);
        newAttributeType28.setDescription("Driver letter of home directory mapping");
        newAttributeType28.setCanUserModify(true);
        newAttributeType28.setSingleValue(true);
        newAttributeType28.setCollective(false);
        newAttributeType28.setObsolete(false);
        newAttributeType28.setLength(4);
        newAttributeType28.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType28.setEqualityId("caseIgnoreIA5Match");
        newAttributeType28.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaHomeDrive");
        newAttributeType28.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.33", newAttributeType28);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType29 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.31", bootstrapRegistries);
        newAttributeType29.setDescription("Timestamp of last logoff");
        newAttributeType29.setCanUserModify(true);
        newAttributeType29.setSingleValue(true);
        newAttributeType29.setCollective(false);
        newAttributeType29.setObsolete(false);
        newAttributeType29.setLength(-1);
        newAttributeType29.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType29.setEqualityId("integerMatch");
        newAttributeType29.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("sambaLogoffTime");
        newAttributeType29.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.31", newAttributeType29);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType30 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.25", bootstrapRegistries);
        newAttributeType30.setDescription("MD4 hash of the unicode password");
        newAttributeType30.setCanUserModify(true);
        newAttributeType30.setSingleValue(true);
        newAttributeType30.setCollective(false);
        newAttributeType30.setObsolete(false);
        newAttributeType30.setLength(32);
        newAttributeType30.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType30.setEqualityId("caseIgnoreIA5Match");
        newAttributeType30.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaNTPassword");
        newAttributeType30.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.25", newAttributeType30);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType31 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.45", bootstrapRegistries);
        newAttributeType31.setDescription("A string option");
        newAttributeType31.setCanUserModify(true);
        newAttributeType31.setSingleValue(true);
        newAttributeType31.setCollective(false);
        newAttributeType31.setObsolete(false);
        newAttributeType31.setLength(-1);
        newAttributeType31.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType31.setEqualityId("caseExactIA5Match");
        newAttributeType31.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaStringOption");
        newAttributeType31.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.45", newAttributeType31);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType32 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.34", bootstrapRegistries);
        newAttributeType32.setDescription("Logon script path");
        newAttributeType32.setCanUserModify(true);
        newAttributeType32.setSingleValue(true);
        newAttributeType32.setCollective(false);
        newAttributeType32.setObsolete(false);
        newAttributeType32.setLength(255);
        newAttributeType32.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType32.setEqualityId("caseIgnoreMatch");
        newAttributeType32.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("sambaLogonScript");
        newAttributeType32.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.34", newAttributeType32);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType33 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.36", bootstrapRegistries);
        newAttributeType33.setDescription("List of user workstations the user is allowed to logon to");
        newAttributeType33.setCanUserModify(true);
        newAttributeType33.setSingleValue(true);
        newAttributeType33.setCollective(false);
        newAttributeType33.setObsolete(false);
        newAttributeType33.setLength(255);
        newAttributeType33.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType33.setEqualityId("caseIgnoreMatch");
        newAttributeType33.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("sambaUserWorkstations");
        newAttributeType33.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.36", newAttributeType33);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType34 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.47", bootstrapRegistries);
        newAttributeType34.setCanUserModify(true);
        newAttributeType34.setSingleValue(false);
        newAttributeType34.setCollective(false);
        newAttributeType34.setObsolete(false);
        newAttributeType34.setLength(IronSourceError.ERROR_DO_IS_LOAD_ALREADY_IN_PROGRESS);
        newAttributeType34.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType34.setEqualityId("caseExactMatch");
        newAttributeType34.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("sambaMungedDial");
        newAttributeType34.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.47", newAttributeType34);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType35 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.23", bootstrapRegistries);
        newAttributeType35.setDescription("Primary Group Security ID");
        newAttributeType35.setCanUserModify(true);
        newAttributeType35.setSingleValue(true);
        newAttributeType35.setCollective(false);
        newAttributeType35.setObsolete(false);
        newAttributeType35.setLength(64);
        newAttributeType35.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType35.setEqualityId("caseIgnoreIA5Match");
        newAttributeType35.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaPrimaryGroupSID");
        newAttributeType35.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.23", newAttributeType35);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType36 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.37", bootstrapRegistries);
        newAttributeType36.setDescription("Home directory UNC path");
        newAttributeType36.setCanUserModify(true);
        newAttributeType36.setSingleValue(false);
        newAttributeType36.setCollective(false);
        newAttributeType36.setObsolete(false);
        newAttributeType36.setLength(128);
        newAttributeType36.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType36.setEqualityId("caseIgnoreMatch");
        newAttributeType36.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("sambaHomePath");
        newAttributeType36.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.37", newAttributeType36);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType37 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.7165.2.1.51", bootstrapRegistries);
        newAttributeType37.setDescription("Security ID List");
        newAttributeType37.setCanUserModify(true);
        newAttributeType37.setSingleValue(false);
        newAttributeType37.setCollective(false);
        newAttributeType37.setObsolete(false);
        newAttributeType37.setLength(64);
        newAttributeType37.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType37.setEqualityId("caseIgnoreIA5Match");
        newAttributeType37.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("sambaSIDList");
        newAttributeType37.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.7165.2.1.51", newAttributeType37);
    }
}
