package org.apache.ldap.server.schema.bootstrap;

import java.util.ArrayList;
import javax.naming.NamingException;
import org.apache.ldap.common.schema.UsageEnum;
import org.apache.ldap.server.db.Database;
import org.apache.ldap.server.jndi.JavaLdapSupport;
import org.apache.ldap.server.schema.bootstrap.AbstractBootstrapProducer;
/* loaded from: classes3.dex */
public class SystemAttributeTypeProducer extends AbstractBootstrapProducer {
    public SystemAttributeTypeProducer() {
        super(ProducerTypeEnum.ATTRIBUTE_TYPE_PRODUCER);
    }

    @Override // org.apache.ldap.server.schema.bootstrap.BootstrapProducer
    public void produce(BootstrapRegistries bootstrapRegistries, ProducerCallback producerCallback) throws NamingException {
        ArrayList arrayList = new ArrayList();
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType = AbstractBootstrapProducer.newAttributeType("2.5.18.4", bootstrapRegistries);
        newAttributeType.setDescription("RFC2252: name of last modifier");
        newAttributeType.setCanUserModify(false);
        newAttributeType.setSingleValue(true);
        newAttributeType.setCollective(false);
        newAttributeType.setObsolete(false);
        newAttributeType.setLength(-1);
        newAttributeType.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType.setEqualityId("distinguishedNameMatch");
        newAttributeType.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("modifiersName");
        newAttributeType.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.18.4", newAttributeType);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType2 = AbstractBootstrapProducer.newAttributeType("2.5.18.12", bootstrapRegistries);
        newAttributeType2.setCanUserModify(false);
        newAttributeType2.setSingleValue(false);
        newAttributeType2.setCollective(false);
        newAttributeType2.setObsolete(false);
        newAttributeType2.setLength(-1);
        newAttributeType2.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType2.setEqualityId("distinguishedNameMatch");
        newAttributeType2.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("collectiveAttributeSubentries");
        newAttributeType2.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.18.12", newAttributeType2);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType3 = AbstractBootstrapProducer.newAttributeType("2.16.840.1.113730.3.1.34", bootstrapRegistries);
        newAttributeType3.setDescription("namedref: subordinate referral URL");
        newAttributeType3.setCanUserModify(true);
        newAttributeType3.setSingleValue(false);
        newAttributeType3.setCollective(false);
        newAttributeType3.setObsolete(false);
        newAttributeType3.setLength(-1);
        newAttributeType3.setUsage(UsageEnum.getUsage("distributedOperation"));
        newAttributeType3.setEqualityId("caseExactMatch");
        newAttributeType3.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("ref");
        newAttributeType3.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.16.840.1.113730.3.1.34", newAttributeType3);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType4 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.1466.101.119.4", bootstrapRegistries);
        newAttributeType4.setDescription("RFC2589: dynamic subtrees");
        newAttributeType4.setCanUserModify(false);
        newAttributeType4.setSingleValue(false);
        newAttributeType4.setCollective(false);
        newAttributeType4.setObsolete(false);
        newAttributeType4.setLength(-1);
        newAttributeType4.setUsage(UsageEnum.getUsage("dSAOperation"));
        newAttributeType4.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("dynamicSubtrees");
        newAttributeType4.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.1466.101.119.4", newAttributeType4);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType5 = AbstractBootstrapProducer.newAttributeType("2.5.21.2", bootstrapRegistries);
        newAttributeType5.setDescription("RFC2252: DIT content rules");
        newAttributeType5.setCanUserModify(true);
        newAttributeType5.setSingleValue(false);
        newAttributeType5.setCollective(false);
        newAttributeType5.setObsolete(false);
        newAttributeType5.setLength(-1);
        newAttributeType5.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType5.setEqualityId("objectIdentifierFirstComponentMatch");
        newAttributeType5.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.16");
        arrayList.clear();
        arrayList.add("dITContentRules");
        newAttributeType5.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.21.2", newAttributeType5);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType6 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.1466.101.120.14", bootstrapRegistries);
        newAttributeType6.setDescription("RFC2252: supported SASL mechanisms");
        newAttributeType6.setCanUserModify(true);
        newAttributeType6.setSingleValue(false);
        newAttributeType6.setCollective(false);
        newAttributeType6.setObsolete(false);
        newAttributeType6.setLength(-1);
        newAttributeType6.setUsage(UsageEnum.getUsage("dSAOperation"));
        newAttributeType6.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("supportedSASLMechanisms");
        newAttributeType6.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.1466.101.120.14", newAttributeType6);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType7 = AbstractBootstrapProducer.newAttributeType("2.5.21.4", bootstrapRegistries);
        newAttributeType7.setDescription("RFC2252: matching rules");
        newAttributeType7.setCanUserModify(true);
        newAttributeType7.setSingleValue(false);
        newAttributeType7.setCollective(false);
        newAttributeType7.setObsolete(false);
        newAttributeType7.setLength(-1);
        newAttributeType7.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType7.setEqualityId("objectIdentifierFirstComponentMatch");
        newAttributeType7.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.30");
        arrayList.clear();
        arrayList.add("matchingRules");
        newAttributeType7.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.21.4", newAttributeType7);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType8 = AbstractBootstrapProducer.newAttributeType("2.5.4.41", bootstrapRegistries);
        newAttributeType8.setDescription("RFC2256: common supertype of name attributes");
        newAttributeType8.setCanUserModify(true);
        newAttributeType8.setSingleValue(false);
        newAttributeType8.setCollective(false);
        newAttributeType8.setObsolete(false);
        newAttributeType8.setLength(32768);
        newAttributeType8.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType8.setEqualityId("caseIgnoreMatch");
        newAttributeType8.setSubstrId("caseIgnoreSubstringsMatch");
        newAttributeType8.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("name");
        newAttributeType8.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.41", newAttributeType8);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType9 = AbstractBootstrapProducer.newAttributeType("2.5.18.6", bootstrapRegistries);
        newAttributeType9.setCanUserModify(true);
        newAttributeType9.setSingleValue(true);
        newAttributeType9.setCollective(false);
        newAttributeType9.setObsolete(false);
        newAttributeType9.setLength(-1);
        newAttributeType9.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType9.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.45");
        arrayList.clear();
        arrayList.add("subtreeSpecification");
        newAttributeType9.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.18.6", newAttributeType9);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType10 = AbstractBootstrapProducer.newAttributeType("2.5.21.5", bootstrapRegistries);
        newAttributeType10.setDescription("RFC2252: attribute types");
        newAttributeType10.setCanUserModify(true);
        newAttributeType10.setSingleValue(false);
        newAttributeType10.setCollective(false);
        newAttributeType10.setObsolete(false);
        newAttributeType10.setLength(-1);
        newAttributeType10.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType10.setEqualityId("objectIdentifierFirstComponentMatch");
        newAttributeType10.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.3");
        arrayList.clear();
        arrayList.add("attributeTypes");
        newAttributeType10.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.21.5", newAttributeType10);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType11 = AbstractBootstrapProducer.newAttributeType("2.5.18.10", bootstrapRegistries);
        newAttributeType11.setDescription("RFC2252: name of controlling subschema entry");
        newAttributeType11.setCanUserModify(false);
        newAttributeType11.setSingleValue(true);
        newAttributeType11.setCollective(false);
        newAttributeType11.setObsolete(false);
        newAttributeType11.setLength(-1);
        newAttributeType11.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType11.setEqualityId("distinguishedNameMatch");
        newAttributeType11.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("subschemaSubentry");
        newAttributeType11.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.18.10", newAttributeType11);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType12 = AbstractBootstrapProducer.newAttributeType("2.5.18.9", bootstrapRegistries);
        newAttributeType12.setDescription("X.501: entry has children");
        newAttributeType12.setCanUserModify(false);
        newAttributeType12.setSingleValue(true);
        newAttributeType12.setCollective(false);
        newAttributeType12.setObsolete(false);
        newAttributeType12.setLength(-1);
        newAttributeType12.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType12.setEqualityId("booleanMatch");
        newAttributeType12.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.7");
        arrayList.clear();
        arrayList.add("hasSubordinates");
        newAttributeType12.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.18.9", newAttributeType12);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType13 = AbstractBootstrapProducer.newAttributeType("2.5.21.1", bootstrapRegistries);
        newAttributeType13.setDescription("RFC2252: DIT structure rules");
        newAttributeType13.setCanUserModify(true);
        newAttributeType13.setSingleValue(false);
        newAttributeType13.setCollective(false);
        newAttributeType13.setObsolete(false);
        newAttributeType13.setLength(-1);
        newAttributeType13.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType13.setEqualityId("integerFirstComponentMatch");
        newAttributeType13.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.17");
        arrayList.clear();
        arrayList.add("dITStructureRules");
        newAttributeType13.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.21.1", newAttributeType13);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType14 = AbstractBootstrapProducer.newAttributeType("2.5.4.35", bootstrapRegistries);
        newAttributeType14.setDescription("RFC2256/2307: password of user");
        newAttributeType14.setCanUserModify(true);
        newAttributeType14.setSingleValue(false);
        newAttributeType14.setCollective(false);
        newAttributeType14.setObsolete(false);
        newAttributeType14.setLength(128);
        newAttributeType14.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType14.setEqualityId("octetStringMatch");
        newAttributeType14.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.40");
        arrayList.clear();
        arrayList.add("userPassword");
        newAttributeType14.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.35", newAttributeType14);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType15 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.1466.101.120.5", bootstrapRegistries);
        newAttributeType15.setDescription("RFC2252: naming contexts");
        newAttributeType15.setCanUserModify(true);
        newAttributeType15.setSingleValue(false);
        newAttributeType15.setCollective(false);
        newAttributeType15.setObsolete(false);
        newAttributeType15.setLength(-1);
        newAttributeType15.setUsage(UsageEnum.getUsage("dSAOperation"));
        newAttributeType15.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("namingContexts");
        newAttributeType15.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.1466.101.120.5", newAttributeType15);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType16 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.1.5", bootstrapRegistries);
        newAttributeType16.setDescription("RFC3045: version of implementation");
        newAttributeType16.setCanUserModify(false);
        newAttributeType16.setSingleValue(true);
        newAttributeType16.setCollective(false);
        newAttributeType16.setObsolete(false);
        newAttributeType16.setLength(-1);
        newAttributeType16.setUsage(UsageEnum.getUsage("dSAOperation"));
        newAttributeType16.setEqualityId("caseExactMatch");
        newAttributeType16.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("vendorVersion");
        newAttributeType16.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.5", newAttributeType16);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType17 = AbstractBootstrapProducer.newAttributeType("2.5.21.7", bootstrapRegistries);
        newAttributeType17.setDescription("RFC2252: name forms ");
        newAttributeType17.setCanUserModify(true);
        newAttributeType17.setSingleValue(false);
        newAttributeType17.setCollective(false);
        newAttributeType17.setObsolete(false);
        newAttributeType17.setLength(-1);
        newAttributeType17.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType17.setEqualityId("objectIdentifierFirstComponentMatch");
        newAttributeType17.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.35");
        arrayList.clear();
        arrayList.add("nameForms");
        newAttributeType17.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.21.7", newAttributeType17);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType18 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.1466.101.120.15", bootstrapRegistries);
        newAttributeType18.setDescription("RFC2252: supported LDAP versions");
        newAttributeType18.setCanUserModify(true);
        newAttributeType18.setSingleValue(false);
        newAttributeType18.setCollective(false);
        newAttributeType18.setObsolete(false);
        newAttributeType18.setLength(-1);
        newAttributeType18.setUsage(UsageEnum.getUsage("dSAOperation"));
        newAttributeType18.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("supportedLDAPVersion");
        newAttributeType18.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.1466.101.120.15", newAttributeType18);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType19 = AbstractBootstrapProducer.newAttributeType("2.5.4.49", bootstrapRegistries);
        newAttributeType19.setDescription("RFC2256: common supertype of DN attributes");
        newAttributeType19.setCanUserModify(true);
        newAttributeType19.setSingleValue(false);
        newAttributeType19.setCollective(false);
        newAttributeType19.setObsolete(false);
        newAttributeType19.setLength(-1);
        newAttributeType19.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType19.setEqualityId("distinguishedNameMatch");
        newAttributeType19.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("distinguishedName");
        newAttributeType19.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.49", newAttributeType19);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType20 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.1466.101.120.6", bootstrapRegistries);
        newAttributeType20.setDescription("RFC2252: alternative servers");
        newAttributeType20.setCanUserModify(true);
        newAttributeType20.setSingleValue(false);
        newAttributeType20.setCollective(false);
        newAttributeType20.setObsolete(false);
        newAttributeType20.setLength(-1);
        newAttributeType20.setUsage(UsageEnum.getUsage("dSAOperation"));
        newAttributeType20.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.26");
        arrayList.clear();
        arrayList.add("altServer");
        newAttributeType20.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.1466.101.120.6", newAttributeType20);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType21 = AbstractBootstrapProducer.newAttributeType("2.5.18.2", bootstrapRegistries);
        newAttributeType21.setDescription("RFC2252: time which object was last modified");
        newAttributeType21.setCanUserModify(false);
        newAttributeType21.setSingleValue(true);
        newAttributeType21.setCollective(false);
        newAttributeType21.setObsolete(false);
        newAttributeType21.setLength(-1);
        newAttributeType21.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType21.setEqualityId("generalizedTimeMatch");
        newAttributeType21.setOrderingId("generalizedTimeOrderingMatch");
        newAttributeType21.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.24");
        arrayList.clear();
        arrayList.add("modifyTimestamp");
        newAttributeType21.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.18.2", newAttributeType21);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType22 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.1466.101.120.7", bootstrapRegistries);
        newAttributeType22.setDescription("RFC2252: supported extended operations");
        newAttributeType22.setCanUserModify(true);
        newAttributeType22.setSingleValue(false);
        newAttributeType22.setCollective(false);
        newAttributeType22.setObsolete(false);
        newAttributeType22.setLength(-1);
        newAttributeType22.setUsage(UsageEnum.getUsage("dSAOperation"));
        newAttributeType22.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.38");
        arrayList.clear();
        arrayList.add("supportedExtension");
        newAttributeType22.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.1466.101.120.7", newAttributeType22);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType23 = AbstractBootstrapProducer.newAttributeType("2.5.18.7", bootstrapRegistries);
        newAttributeType23.setCanUserModify(true);
        newAttributeType23.setSingleValue(false);
        newAttributeType23.setCollective(false);
        newAttributeType23.setObsolete(false);
        newAttributeType23.setLength(-1);
        newAttributeType23.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType23.setEqualityId("objectIdentifierMatch");
        newAttributeType23.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.38");
        arrayList.clear();
        arrayList.add("collectiveExclusions");
        newAttributeType23.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.18.7", newAttributeType23);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType24 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.1.4", bootstrapRegistries);
        newAttributeType24.setDescription("RFC3045: name of implementation vendor");
        newAttributeType24.setCanUserModify(false);
        newAttributeType24.setSingleValue(true);
        newAttributeType24.setCollective(false);
        newAttributeType24.setObsolete(false);
        newAttributeType24.setLength(-1);
        newAttributeType24.setUsage(UsageEnum.getUsage("dSAOperation"));
        newAttributeType24.setEqualityId("caseExactMatch");
        newAttributeType24.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("vendorName");
        newAttributeType24.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.1.4", newAttributeType24);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType25 = AbstractBootstrapProducer.newAttributeType("2.5.18.5", bootstrapRegistries);
        newAttributeType25.setCanUserModify(true);
        newAttributeType25.setSingleValue(false);
        newAttributeType25.setCollective(false);
        newAttributeType25.setObsolete(false);
        newAttributeType25.setLength(-1);
        newAttributeType25.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType25.setEqualityId("objectIdentifierMatch");
        newAttributeType25.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.38");
        arrayList.clear();
        arrayList.add("administrativeRole");
        newAttributeType25.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.18.5", newAttributeType25);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType26 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.250.1.57", bootstrapRegistries);
        newAttributeType26.setDescription("RFC2079: Uniform Resource Identifier with optional label");
        newAttributeType26.setCanUserModify(true);
        newAttributeType26.setSingleValue(false);
        newAttributeType26.setCollective(false);
        newAttributeType26.setObsolete(false);
        newAttributeType26.setLength(-1);
        newAttributeType26.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType26.setEqualityId("caseExactMatch");
        newAttributeType26.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.15");
        arrayList.clear();
        arrayList.add("labeledURI");
        newAttributeType26.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.250.1.57", newAttributeType26);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType27 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.1466.101.119.3", bootstrapRegistries);
        newAttributeType27.setDescription("RFC2589: entry time-to-live");
        newAttributeType27.setCanUserModify(false);
        newAttributeType27.setSingleValue(true);
        newAttributeType27.setCollective(false);
        newAttributeType27.setObsolete(false);
        newAttributeType27.setLength(-1);
        newAttributeType27.setUsage(UsageEnum.getUsage("dSAOperation"));
        newAttributeType27.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.27");
        arrayList.clear();
        arrayList.add("entryTtl");
        newAttributeType27.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.1466.101.119.3", newAttributeType27);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType28 = AbstractBootstrapProducer.newAttributeType("2.5.18.1", bootstrapRegistries);
        newAttributeType28.setDescription("RFC2252: time which object was created");
        newAttributeType28.setCanUserModify(false);
        newAttributeType28.setSingleValue(true);
        newAttributeType28.setCollective(false);
        newAttributeType28.setObsolete(false);
        newAttributeType28.setLength(-1);
        newAttributeType28.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType28.setEqualityId("generalizedTimeMatch");
        newAttributeType28.setOrderingId("generalizedTimeOrderingMatch");
        newAttributeType28.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.24");
        arrayList.clear();
        arrayList.add("createTimestamp");
        newAttributeType28.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.18.1", newAttributeType28);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType29 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.1466.101.120.13", bootstrapRegistries);
        newAttributeType29.setDescription("RFC2252: supported controls");
        newAttributeType29.setCanUserModify(true);
        newAttributeType29.setSingleValue(false);
        newAttributeType29.setCollective(false);
        newAttributeType29.setObsolete(false);
        newAttributeType29.setLength(-1);
        newAttributeType29.setUsage(UsageEnum.getUsage("dSAOperation"));
        newAttributeType29.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.38");
        arrayList.clear();
        arrayList.add("supportedControl");
        newAttributeType29.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.1466.101.120.13", newAttributeType29);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType30 = AbstractBootstrapProducer.newAttributeType("2.5.4.1", bootstrapRegistries);
        newAttributeType30.setDescription("RFC2256: name of aliased object");
        newAttributeType30.setCanUserModify(true);
        newAttributeType30.setSingleValue(true);
        newAttributeType30.setCollective(false);
        newAttributeType30.setObsolete(false);
        newAttributeType30.setLength(-1);
        newAttributeType30.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType30.setEqualityId("distinguishedNameMatch");
        newAttributeType30.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add(Database.ALIAS_ATTRIBUTE);
        arrayList.add("aliasedEntryName");
        newAttributeType30.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.1", newAttributeType30);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType31 = AbstractBootstrapProducer.newAttributeType("2.5.21.9", bootstrapRegistries);
        newAttributeType31.setDescription("X.500(93): structural object class of entry");
        newAttributeType31.setCanUserModify(false);
        newAttributeType31.setSingleValue(true);
        newAttributeType31.setCollective(false);
        newAttributeType31.setObsolete(false);
        newAttributeType31.setLength(-1);
        newAttributeType31.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType31.setEqualityId("objectIdentifierMatch");
        newAttributeType31.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.38");
        arrayList.clear();
        arrayList.add("structuralObjectClass");
        newAttributeType31.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.21.9", newAttributeType31);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType32 = AbstractBootstrapProducer.newAttributeType("2.5.21.8", bootstrapRegistries);
        newAttributeType32.setDescription("RFC2252: matching rule uses");
        newAttributeType32.setCanUserModify(true);
        newAttributeType32.setSingleValue(false);
        newAttributeType32.setCollective(false);
        newAttributeType32.setObsolete(false);
        newAttributeType32.setLength(-1);
        newAttributeType32.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType32.setEqualityId("objectIdentifierFirstComponentMatch");
        newAttributeType32.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.31");
        arrayList.clear();
        arrayList.add("matchingRuleUse");
        newAttributeType32.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.21.8", newAttributeType32);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType33 = AbstractBootstrapProducer.newAttributeType("2.5.4.0", bootstrapRegistries);
        newAttributeType33.setDescription("RFC2256: object classes of the entity");
        newAttributeType33.setCanUserModify(true);
        newAttributeType33.setSingleValue(false);
        newAttributeType33.setCollective(false);
        newAttributeType33.setObsolete(false);
        newAttributeType33.setLength(-1);
        newAttributeType33.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType33.setEqualityId("objectIdentifierMatch");
        newAttributeType33.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.38");
        arrayList.clear();
        arrayList.add(JavaLdapSupport.OBJECTCLASS_ATTR);
        newAttributeType33.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.0", newAttributeType33);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType34 = AbstractBootstrapProducer.newAttributeType("1.3.6.1.4.1.1466.101.120.16", bootstrapRegistries);
        newAttributeType34.setDescription("RFC2252: LDAP syntaxes");
        newAttributeType34.setCanUserModify(true);
        newAttributeType34.setSingleValue(false);
        newAttributeType34.setCollective(false);
        newAttributeType34.setObsolete(false);
        newAttributeType34.setLength(-1);
        newAttributeType34.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType34.setEqualityId("objectIdentifierFirstComponentMatch");
        newAttributeType34.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.54");
        arrayList.clear();
        arrayList.add("ldapSyntaxes");
        newAttributeType34.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "1.3.6.1.4.1.1466.101.120.16", newAttributeType34);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType35 = AbstractBootstrapProducer.newAttributeType("2.5.4.3", bootstrapRegistries);
        newAttributeType35.setDescription("RFC2256: common name(s) for which the entity is known by");
        newAttributeType35.setCanUserModify(true);
        newAttributeType35.setSingleValue(false);
        newAttributeType35.setCollective(false);
        newAttributeType35.setObsolete(false);
        newAttributeType35.setLength(-1);
        newAttributeType35.setUsage(UsageEnum.getUsage("userApplications"));
        newAttributeType35.setSuperiorId("name");
        arrayList.clear();
        arrayList.add("cn");
        arrayList.add("commonName");
        newAttributeType35.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.4.3", newAttributeType35);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType36 = AbstractBootstrapProducer.newAttributeType("2.5.18.3", bootstrapRegistries);
        newAttributeType36.setDescription("RFC2252: name of creator");
        newAttributeType36.setCanUserModify(false);
        newAttributeType36.setSingleValue(true);
        newAttributeType36.setCollective(false);
        newAttributeType36.setObsolete(false);
        newAttributeType36.setLength(-1);
        newAttributeType36.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType36.setEqualityId("distinguishedNameMatch");
        newAttributeType36.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.12");
        arrayList.clear();
        arrayList.add("creatorsName");
        newAttributeType36.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.18.3", newAttributeType36);
        AbstractBootstrapProducer.BootstrapAttributeType newAttributeType37 = AbstractBootstrapProducer.newAttributeType("2.5.21.6", bootstrapRegistries);
        newAttributeType37.setDescription("RFC2252: object classes");
        newAttributeType37.setCanUserModify(true);
        newAttributeType37.setSingleValue(false);
        newAttributeType37.setCollective(false);
        newAttributeType37.setObsolete(false);
        newAttributeType37.setLength(-1);
        newAttributeType37.setUsage(UsageEnum.getUsage("directoryOperation"));
        newAttributeType37.setEqualityId("objectIdentifierFirstComponentMatch");
        newAttributeType37.setSyntaxId("1.3.6.1.4.1.1466.115.121.1.37");
        arrayList.clear();
        arrayList.add("objectClasses");
        newAttributeType37.setNames((String[]) arrayList.toArray(AbstractBootstrapProducer.EMPTY));
        producerCallback.schemaObjectProduced(this, "2.5.21.6", newAttributeType37);
    }
}
